- include/coro_rpc/coro_rpc/rpc_protocol.h
fix expected conditional compilation
using std::expected if supported & enable C++23, otherwise we use coro_rpc::expected
> fix expected conditional compilation

- README.md
- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/doc/Introduction_CN.md
- src/struct_pack/doc/struct_pack_doc.hpp
- src/struct_pack/examples/serialize/serialize.cpp
- src/struct_pack/tests/test_serialize.cpp
`struct_pack::expected` is easier for use.
If you don't want to check error explicitly. it will throw exception when you access value。
Otherwise, you can use `if (result) {...}` to instead of  `if (err==std::errc{}) {...}`。
Like get_field, but return value by reference.
> Add get_field_to & use expected as deserialize_result

- include/struct_pack/struct_pack.hpp
- src/struct_pack/doc/Introduction_CN.md
- src/struct_pack/doc/struct_pack_doc.hpp
- src/struct_pack/tests/test_serialize.cpp
struct_pack::deserialize now support varadic parameters.
Add document & test. 
```cpp
struct_pack::deserialize<int,double,std::string>(buffer);
// as same as:
// struct_pack::deserialize<std::tuple<int,double,std::string>>(buffer);
```
> add deserialize varadic support & it's document

- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/doc/struct_pack_doc.hpp
- src/struct_pack/examples/serialize/serialize.cpp
- src/struct_pack/tests/test_serialize.cpp
Add support for varadic deserialize_to
Now deserialize_to allow variadic params.
Unfortunately, C++'s template type deduction can't work when the variadic is not in the end of parameters. So we have to add   the variadic at the end of paramters.
```cpp
struct person
{
size_t id;
};
struct Book
{
size_t id;
};
person p;
Book b;
//...
auto buffer=struct_pack::serialize("Betty"sv,"The Book"sv);
//...
struct_pack::deserialize_to(p.name,buffer,b.name);
assert(p.name=="Betty");
assert(b.name=="The Book");
```
> add deserialize variadic support & it's document

- include/logging/easylog.hpp
The filesystem::path's value_type is wchar_t in windows, and spdlog don't support wchar_t.
Convert filesystem::path to std::string, instead of get the native string.
> [coro_rpc] Fix the problem that filesystem::path::c_str() can't be logged in windows.

- src/coro_rpc/examples/CMakeLists.txt
- src/coro_rpc/examples/file_transfer/CMakeLists.txt
- src/coro_rpc/examples/file_transfer/file_client/main.cpp
- src/coro_rpc/examples/file_transfer/file_server/main.cpp
- src/coro_rpc/examples/file_transfer/file_server/rpc_service.cpp
- src/coro_rpc/examples/file_transfer/rpc_service/rpc_service.h
Add a file transfer example for coro_rpc, to show how to use coro_rpc upload files.
> add file transfer example

- .github/workflows/linux_llvm_cov.yml
https://github.com/peter-evans/create-or-update-comment
In public repositories this action does not work in pull_request workflows when triggered by forks. Any attempt will be met with the error, Resource not accessible by integration. This is due to token restrictions put in place by GitHub Actions. Private repositories can be configured to [enable workflows](https://docs.github.com/en/github/administering-a-repository/disabling-or-limiting-github-actions-for-a-repository#enabling-workflows-for-private-repository-forks) from forks to run without restriction. See [here](https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#restrictions-on-repository-forks) for further explanation. Alternatively, use the …
> fix: Resource not accessible by integration

- NOTICE
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- include/struct_pack/struct_pack/tuple.hpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_serialize.cpp
- src/struct_pack/tests/test_tuplet.cpp
std::tuple is not trivial copyable type, we need a trivial copyable tuple, so import [tuplet](https://github.com/codeinred/tuplet)
> import tuplet

- src/coro_rpc/CMakeLists.txt
add option for enable io_uring in linux.
add cmake option ENABLE_IO_URING
> [coro_rpc] add optional for enable io_uring in linux

- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_alignas.cpp
- src/struct_pack/tests/test_pragma_pack.cpp
- src/struct_pack/tests/test_pragma_pack_and_alignas_mix.cpp
- src/struct_pack/tests/test_serialize.cpp
handle Case 1: Struct Align of https://github.com/alibaba/yalantinglibs/issues/45
One of the low-level features of C++ is the ability to specify the precise alignment of objects in memory to take maximum advantage of a specific hardware architecture.
In most scenarios, you never have to be concerned with alignment because the default alignment is already optimal. In some cases, however, you can achieve significant performance improvements, or memory savings, by specifying a custom alignment for your data structures. 
So, How do we handle these behavior?
We add the alignment requirement to the end of struct_pack type tree, before doing hash. 
To implement the check, let's look at the C++ alignment requirement first.
On the one hand, the C++11 standard introduces the keywords `alignof` and …
> [struct_pack] check alignment requirement

- include/coro_rpc/coro_rpc/async_rpc_server.hpp
- include/coro_rpc/coro_rpc/coro_rpc_server.hpp
- src/coro_rpc/CMakeLists.txt
Fix port in use for msvc, and disable iocp to avoid a bug: socket destruct after io_context destruct will cause crash, but it's ok on linux, so disable win iocp to avoid the bug.
> fix port in use for msvc; disable iocp

- include/asio_util/asio_coro_util.hpp
- include/coro_rpc/coro_rpc/coro_connection.hpp
- include/coro_rpc/coro_rpc/coro_rpc_client.hpp
- include/coro_rpc/coro_rpc/coro_rpc_server.hpp
- src/coro_rpc/benchmark/api/rpc_functions.hpp
asio_util has too many bored codes.
Add asio_util::callback_awaitor to instead of bored awaitors.
```cpp
async_simple::Lazy<std::pair<std::error_code,size_t>> 
async_write_some(asio::stream_file& file,std::string_view my_buffer) {
asio_util::callback_awaitor<std::pair<std::error_code,size_t>> awaitor;
co_return co_await awaitor.await_resume([&]{
file.async_write_some(my_buffer, [&](std::error_code e, size_t n)
{
awaitor.set_value_then_resume(e,n);
});
});
}
```
> [coro_rpc] enhance asio_util. Add callback_awaitor

- README.md
- src/coro_rpc/doc/coro_rpc_introduction_cn.md
- src/coro_rpc/doc/coro_rpc_introduction_en.md
The document is outdated. 
`client.connect("localhost", 9000)` howerver the 2nd parameter should be "9000"
doc
NA
> update the doc: client connect port is std::string type

- include/coro_rpc/coro_rpc/async_connection.hpp
- include/coro_rpc/coro_rpc/coro_connection.hpp
- include/coro_rpc/coro_rpc/coro_rpc_client.hpp
- include/coro_rpc/coro_rpc/router_impl.hpp
- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/error_code.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/coro_rpc/tests/test_async_rpc_server.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_remote.cpp
- src/struct_pack/examples/serialize/serialize.cpp
- src/struct_pack/tests/test_serialize.cpp
std::errc is not enough for struct_pack, so add struct_pack error code. 
std::errc to struct_pack::errc
> add struct_pack error code

- include/coro_rpc/coro_rpc/rpc_protocol.h
- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/error_code.h
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/benchmark/benchmark.cpp
- src/struct_pack/doc/struct_pack_doc.hpp
- src/struct_pack/tests/test_serialize.cpp
Now struct_pack can detected hash conflict in deserialization. 
Add full type info when the NDEBUG marco was not defined. Then we will check it in deserialization.
> [struct pack] Detect hash conflict in debug mode

- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/md5_constexpr.hpp
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/coro_rpc/tests/CMakeLists.txt
- src/struct_pack/benchmark/CMakeLists.txt
- src/struct_pack/benchmark/benchmark.cpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_compile_time_calculate.cpp
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_data_struct2.cpp
- src/struct_pack/tests/test_serialize.cpp
- src/struct_pack/tests/test_struct.hpp
The container's size is fixed which is defined by a marco in old version struct_pack. However, it's hard to determine the max size of container/string in compile time. And the binary with different width of container size is not portable.
Now we support variant container size in runtime. User don't need to worry about if they have a big string(There is no limit now).
If the max size of all container in the struct is in the range of [0,256), the size_type's length is 1 byte.   
[0,256) ->1 byte size_type
[256,65536) -> 2 bytes size_type   
[65536,2^32) -> 4 bytes size_type
[2^32,2^64)-> 8 bytes size_type
In Clang 13, The performance is even better (about 10% in serialize & 5% in deserialization) than the old version due to the decrease size of serialize result. However, due to the template …
> Support variant container size

- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_serialize.cpp
Fix variant Layout.
Now variant index only use 1 bytes in serialize result.
struct_pack serialize will naturely throw exception by std::visit if variant is valueless by exception now.
> Fix variant layout

- cmake/platform.cmake
Closes #99
Add option `/EHa` for msvc to workaround Compile Error C4737 in msvc release.
> [coro_rpc] Workaround for MSVC C4737.

- .github/workflows/linux_clang.yml
- .github/workflows/linux_gcc.yml
- .github/workflows/mac.yml
- .github/workflows/windows.yml
- cmake/module.cmake
CI is very slow for the project
every platfome use ninja as Cmake-generator and Cmake-Makeprogram . 
This version with ninja will be the fastest CI version !!!
add win32 support for CI . 
with ninja CI test for win64 and win32 faster than win64 only. haha 
Window Server with  `msvc+msbuild` `cmake-configure 9min` `cmake-generate 16min`
But now, when you ues ninja   `msvc+ninja` `cmake-configure 20s` `cmake-generate 6min`
By the way , linux ,macos CI will improve too.
I have tested before  pr , all you want to know about `CI impovement ` can be found at my own fork.
website here ..........
https://github.com/sunflower-knight/yalantinglibs/actions
Strongly recommend developers can accept this pr
##Add`
it will be easier for developer to test `window-across-platform` in the new …
> use ninja for ci and add win32

- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_alignas.cpp
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_pragma_pack.cpp
- src/struct_pack/tests/test_pragma_pack_and_alignas_mix.cpp
- src/struct_pack/tests/test_serialize.cpp
- src/struct_pack/tests/test_struct.hpp
struct_pack should support recursion type. So we should support pointer/references.
Add support for unique_ptr-like pointer.
```cpp
struct my_tree {
std::unique_ptr<my_tree> left_child;
std::unique_ptr<my_tree> right_child;
int value;
};
my_tree root;
auto buffer=struct_pack::serialize(root);
auto result=struct_pack::deserialize(buffer);
//CHECK(root == result);
```
```cpp
```
> [struct_pack] Add support for unique_ptr

- cmake/platform.cmake
- include/coro_rpc/coro_rpc/async_connection.hpp
- include/coro_rpc/coro_rpc/coro_connection.hpp
- include/coro_rpc/coro_rpc/coro_rpc_client.hpp
- include/coro_rpc/coro_rpc/rpc_protocol.h
- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/error_code.h
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- include/struct_pack/struct_pack/varint.hpp
- src/coro_rpc/tests/test_async_rpc_server.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_register_handler.cpp
- src/struct_pack/doc/Introduction_CN.md
- src/struct_pack/doc/Introduction_EN.md
- src/struct_pack/doc/struct_pack_doc.hpp
- src/struct_pack/examples/serialize/serialize.cpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_serialize.cpp
- src/struct_pack/tests/test_stream.cpp
- src/struct_pack/tests/test_struct.hpp
struct_pack should support serialize to stream(like file,socket,pipeline...)
Fix the #143 too.
Refactor the struct_pack. Now it can serialize/deserialize to stream.
struct_pack::writer_t is a concept: 
```cpp
template <typename T>
concept writer_t = requires(T t) {
t.write((const char *){}, std::size_t{});
};
```
istream/sstream is a writer, and it's easy for user to write an wrapper code for socket,pipe……
struct_pack::reader_t is a concept: 
```cpp
template <typename T>
concept reader_t = requires(T t) {
t.read((char *)nullptr, std::size_t{}); 
t.ignore(std::size_t{});
t.tellg();
};
```
ostream/sstream is a reader, and it's easy for user to write an wrapper code for socket,pipe……
struct_pack::get_needed_size now return a class struct_pack::serialize_buffer_size. This class is read-only …
> [struct_pack] Add support for serialize to stream

- .gitignore
- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_compatible.cpp
- src/struct_pack/tests/test_compile_time_calculate.cpp
- src/struct_pack/tests/test_serialize.cpp
Improve struct_pack::compatible
Relax the limit of compatible field. You can add it in any place of struct, even in nested struct or in the container.
Add the version number for `struct_pack::compatible`. The default version number is 1. 
```cpp
struct person_v0 {
uint64_t ID;
struct course {
}
std::vector<course> courses;
};
struct person_v1 {
uint64_t ID;
struct course {
}
std::vector<course> courses;
struct_pack::compatible<uint32_t> age; //the default version number is 1.
};
struct person_v2 { //update at 2023/01/11
uint64_t ID;
struct course {
struct_pack::compatible<uint64_t, 20230111> ID;
struct_pack::compatible<double, 20230111> GPA;
}
std::vector<course> courses; …
```
> [struct_pack] Improve compatible

- CMakeLists.txt
- cmake/dependency.cmake
Possible solution for [#156](https://github.com/alibaba/yalantinglibs/issues/156)
Executing cmake compile command in vcpkg ci pipeline (or minimize ubuntu 20.04) gives error
move find_package(Threads REQUIRED) in cmake/dependency.cmake to project-root folder to avoid this error.
- move find_package(Threads REQUIRED) in cmake/dependency.cmake to project-root folder
> fix cmake error in minimize ubuntu 20.04 and vcpkg ci pipeline

- include/coro_rpc/coro_rpc/coro_rpc_client.hpp
Fix a bug:client call a coroutine function with right value will cause temporaries release after co_await.
> avoid rvalue ref in coroutine functions

- include/coro_rpc/coro_rpc/coro_rpc_client.hpp
- include/coro_rpc/coro_rpc/rpc_protocol.h
- src/coro_rpc/examples/helloworld/client/main.cpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_router.cpp
Don‘t create a thread to join client io thread when ~client() running in io thread, just detach itself.
> [coro_rpc] fix client join itself

- include/coro_rpc/coro_rpc/coro_rpc_server.hpp
- include/coro_rpc/coro_rpc/router.hpp
- include/coro_rpc/coro_rpc/router_impl.hpp
- src/coro_rpc/tests/ServerTester.hpp
- src/coro_rpc/tests/rpc_api.hpp
- src/coro_rpc/tests/rpc_service.cpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_register_handler.cpp
Don't need to remove_hander anymore, because the handlers are not global and in the server now.
> remove remove_handler method

- include/asio_util/asio_coro_util.hpp
- include/coro_rpc/coro_rpc_server.hpp
- build demo code fail
- `SimpleExecutor` is not a necessary dependency
- change `async_simple/executors/SimpleExecutor.h` to `async_simple/Executor.h`
- add `coro_rpc/coro_rpc/router_impl.hpp` to `coro_rpc/coro_rpc_server.hpp `
- https://github.com/PikachuHyA/yalantinglibs_as_submodule_demo
- https://github.com/PikachuHyA/yalantinglibs_find_package_demo
> fix header

- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_serialize.cpp
The gcc 12.2.0 in Ubuntu 20.10 crash when compile test_serialize. See #209 
We make a workaround for struct_pack::detail::get_types to avoid gcc crash.
There is no interface changed.
> [struct_pack] workaround for gcc 12.2

- include/coro_rpc/coro_rpc/coro_rpc_server.hpp
- include/coro_rpc/coro_rpc/router.hpp
- src/coro_rpc/benchmark/server.hpp
- src/coro_rpc/doc/coro_rpc_doc.hpp
- src/coro_rpc/doc/coro_rpc_introduction_cn.md
- src/coro_rpc/doc/coro_rpc_introduction_en.md
- src/coro_rpc/examples/file_transfer/file_server/main.cpp
- src/coro_rpc/examples/helloworld/server/main.cpp
- src/coro_rpc/examples/user_defined_rpc_protocol/rest_rpc/server/main.cpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_register_duplication_1.cpp
- src/coro_rpc/tests/test_register_duplication_2.cpp
- src/coro_rpc/tests/test_register_duplication_3.cpp
- src/coro_rpc/tests/test_router.cpp
- src/coro_rpc/tests/test_variadic.cpp
fix the error pronounce of register_handler
rename coro_rpc_server::regist_handler to coro_rpc_server::register_hander
> [coro_rpc] fix register_handler

- gen_doc.sh
zh page style error. a fix method for #214 
update gen_doc.sh
traversal the html files under docs/zh and modify the missing class to fix style bug.
> fix: fix zh page style on gen_doc.sh(#214)

- gen_doc.sh
zh page style error.
update gen_doc.sh
traversal the html files under docs/zh and modify the missing class to fix style bug.
> fix: fix style on gen_doc.sh(#214)

- include/util/function_name.h
- include/util/magic_names.hpp
- include/util/meta_string.hpp
- include/util/type_traits.h
- src/coro_rpc/tests/test_util.cpp
- src/easylog/tests/CMakeLists.txt
Let magic name and meta string compile in c++17, because some users use gcc8.3 and clang11.
> let magic name support c++17

- src/coro_http/CMakeLists.txt
- src/coro_http/examples/main.cpp
fix example build fail when `ENABLE_SSL` is ON
- `target_compile_definitions(coro_http INTERFACE ENABLE_SSL)`
> [coro_http] fix example build fail with openssl

- include/asio_util/asio_coro_util.hpp
- include/coro_rpc/coro_rpc/context.hpp
- include/coro_rpc/coro_rpc/coro_connection.hpp
- include/coro_rpc/coro_rpc/protocol/coro_rpc_protocol.hpp
- include/coro_rpc/coro_rpc/router.hpp
- include/coro_rpc/coro_rpc/rpc_execute.hpp
- src/coro_http/examples/main.cpp
- src/coro_rpc/examples/helloworld/server/main.cpp
- src/coro_rpc/tests/ServerTester.hpp
- src/coro_rpc/tests/rpc_service.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_router.cpp
1. fix body's buffer ownership
2. allow delay rpc function call
> [coro_rpc] allow delay rpc call, context now share the ownership of body's buffer with connection

- src/coro_http/CMakeLists.txt
fix https://github.com/alibaba/yalantinglibs/issues/247 
- typo: `coro_rpc` -> `coro_http`
> [coro_http] fix example build fail due to typo

- include/struct_pack/struct_pack/reflection.h
- include/struct_pack/struct_pack/struct_pack_impl.hpp
- src/struct_pack/benchmark/no_op.cpp
- src/struct_pack/tests/test_alignas.cpp
- src/struct_pack/tests/test_compatible.cpp
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_pragma_pack.cpp
- src/struct_pack/tests/test_pragma_pack_and_alignas_mix.cpp
fix compatible bug in pod.
```
struct foo_v1 {
int a;
double b;
};
struct foo_v2 {
int a;
struct_pack::compatible<std::string> c;
double b;
};
struct foo_v3 {
int a;
struct_pack::compatible<std::string> c;
double b;
struct_pack::compatible<char> d;
};
```
the 2nd/3rd version of foo is not compatible with the 1st version because foo_v1 has optimized pod layout but foo_v2 & foo_v3 has normal layout.
The new layout of foo_v2 & foo_v3 is like:
```
struct foo_v2_equal_layout {
struct foo_v1{
int a;
double b;
} old_part;
struct_pack::compatible<std::string> c;
};
struct foo_v3_equal_layout {
struct foo_v1{
int a;
double b;
} old_part;
struct_pack::compatible<std::string> c;
struct_pack::compatible<char> d;
};
```
Now the old part of  foo_v2 & foo_v3 still has optimized pod layout.
> [struct_pack] fix compatible<T> in pod

- .github/workflows/update_cache.yml
- .github/workflows/website.yml
"Closes #270 "
developers can update website in branch doc or website, in this way there will be fewer  commits in branch main.
every time a push in doc or website will call the website CI.
Dont worry about we  change the original website.
Every day in 1:00 Chinese time  , the website will CI with branch main .You can also call the Ci by yourself in anytime. I make the workflow "called " 
```yml
workflow_dispatch:
workflow_call:
```
It is a solution now for developer who want to change website file.
In the future I will try to make different branch webiste deploy in different url such as "/yalanting-doc/coro_rpc" to make it better to develop.
> change website CI branch and logic

- include/struct_pack/struct_pack/struct_pack_impl.hpp
Now we can use non-aggregate type. But we need to add reflection info manually.
See #278 
Disable check for aggregate. 
```cpp
template <size_t out>
struct stat1 {
std::array<int, out> sb = init_sb();
friend bool operator==(const stat1&, const stat1&) = default;
init1() {
for (int i = 0; i < out; i++) {
sb[i] = rand() % 100;
}
}
};
template <size_t in, size_t out>
struct person1 {
int age;
std::array<stat1<out>, in> state;
friend bool operator==(const person1&, const person1&) = default;
};
// manually add reflection info
template <size_t out>
constexpr std::size_t struct_pack::members_count<stat1<out>> = 1;
template <size_t in, size_t out>
constexpr std::size_t struct_pack::members_count<person1<in, out>> = 3;
```
> [struct_pack] relax the limitation for non-aggregate type.

- thirdparty/iguana/iguana/detail/string_stream.hpp
add pmr control macro for struct_json
> update for gcc11

- include/struct_pack/struct_pack.hpp
- include/struct_pack/struct_pack/md5_constexpr.hpp
- include/struct_pack/struct_pack/struct_pack_impl.hpp
test router test failed with clang old version, so test it.
> fix for clang old version

- include/util/time_util.h
- src/coro_rpc/tests/CMakeLists.txt
- src/coro_rpc/tests/test_time_util.cpp
- thirdparty/cinatra/cinatra/define.h
- thirdparty/cinatra/cinatra/utils.hpp
Add some faster time util functions: date time string to int is 3 times faster than Google's cctz lib.
> add time util

- include/struct_pack/struct_pack/md5_constexpr.hpp
1. 此处返回类型直接设置为auto 优于 decltype(auto ) ，因为内部返回数据没有引用和const 修饰等。
2. 变量类型前置声明。
3. 第二个循环中，直接使用 i + Len1 作为索引，避免 i - Len1 的计算。i+offset 可读性更好
> [struct_pack:readability] improve string_literal readability

- thirdparty/cinatra/cinatra/coro_http_client.hpp
Add allocated buffer for http client, sometimes it can used to avoid memcpy.
> add allocated buffer for http client

- BUILD.bazel
- include/easylog/appender.hpp
- include/easylog/easylog.h
- include/easylog/record.hpp
- src/easylog/benchmark/CMakeLists.txt
- src/easylog/benchmark/main.cpp
- src/easylog/tests/BUILD.bazel
- src/easylog/tests/CMakeLists.txt
- src/easylog/tests/test_easylog.cpp
- thirdparty/iguana/iguana/reflection.hpp
Improve performance of easylog, add async log.
> support async easylog

- src/struct_pb/protoc-plugin/CMakeLists.txt
- website/docs/en/coro_rpc/coro_rpc_introduction.md
- website/docs/en/struct_pack/struct_pack_intro.md
- website/docs/en/struct_pack/struct_pack_layout.md
- website/docs/en/struct_pack/struct_pack_tips.md
- website/docs/en/struct_pb/struct_pb_quick_start.md
- website/docs/zh/coro_rpc/coro_rpc_introduction.md
- website/docs/zh/struct_pack/struct_pack_intro.md
- website/docs/zh/struct_pack/struct_pack_layout.md
- website/docs/zh/struct_pack/struct_pack_tips.md
- website/docs/zh/struct_pb/struct_pb_quick_start.md
> [Doc] fix link

- include/ylt/struct_pack/reflection.hpp
- include/ylt/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_serialize.cpp
- website/docs/en/struct_pack/struct_pack_type_system.md
complete potion TODO
support int128 uint128 with gcc or clang
TEST_CASE("int128/uint128") {
using int128_t = __int128;
using uint128_t = signed __int128;
{
int128_t it = -2131231231213123;
auto ts = struct_pack::serialize(it);
auto it_ = struct_pack::deserialize<int128_t>(ts);
CHECK(it == it_);
}
{
uint128_t it = 2131231231213123;
auto ts = struct_pack::serialize(it);
auto it_ = struct_pack::deserialize<uint128_t>(ts);
CHECK(it == it_);
}
}
> support int128 uint128 with gcc or clang

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_http/examples/CMakeLists.txt
- src/coro_io/examples/CMakeLists.txt
- src/coro_rpc/examples/base_examples/CMakeLists.txt
- src/coro_rpc/examples/base_examples/channel.cpp
- src/coro_rpc/examples/base_examples/client_pools.cpp
- src/coro_rpc/examples/base_examples/concurrent_clients.cpp
- src/coro_rpc/tests/ServerTester.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_variadic.cpp
In the old version of coro_rpc/coro_http, if user don't specify a executor in constructor, the coro_rpc_client/coro_http_client will use a inner io_context, which performance is poor.
No more inner io_context/thread in coro_rpc_client/coro_http_client now. In default, the client will get a executor from global executor pool.
> [coro_rpc] [coro_http] use global executor instead of inner io_context

- include/ylt/easylog.hpp
- include/ylt/easylog/appender.hpp
> fix async console

- include/ylt/easylog.hpp
- include/ylt/easylog/appender.hpp
> [easylog] async console log as default

- include/ylt/easylog/appender.hpp
windows console no color.add it!
easylog appender.hpp
api as same.don't change.
> feat:easylog windows console add color

- include/ylt/coro_rpc/impl/common_service.hpp
mark the paramater "path" of the function "file_exists" as const
Closes #373
> [coro_rpc] mark the paramater as const

- include/ylt/coro_io/client_pool.hpp
when connection close, we should immediately try reconnect at first time.
immediately reconnect at first time.
> [coro_io] reconnect immediately at first try

- README.md
- include/ylt/struct_json/json_reader.h
- include/ylt/struct_pack/reflection.hpp
- include/ylt/thirdparty/iguana/define.h
- include/ylt/thirdparty/iguana/detail/traits.hpp
- include/ylt/thirdparty/iguana/error_code.h
- include/ylt/thirdparty/iguana/json_reader.hpp
- include/ylt/thirdparty/iguana/json_util.hpp
- include/ylt/thirdparty/iguana/json_writer.hpp
- include/ylt/thirdparty/iguana/prettify.hpp
- include/ylt/thirdparty/iguana/reflection.hpp
- include/ylt/thirdparty/iguana/xml_reader.hpp
- include/ylt/thirdparty/iguana/xml_util.hpp
- include/ylt/thirdparty/iguana/yaml_util.hpp
- website/docs/zh/guide/what_is_yalantinglibs.md
Optimize struct_json performance, if open ENABLE_SEQUENTIAL_PARSE will get better performance when struct fields sequence are the same with json structure.
add numeric_str to support lazy parse number.
> Update struct json

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
bug fix: avoid visit client member variable after client destruct.
> [coro_http][bugfix] fix coroutine quit after client destruct

- include/ylt/coro_io/client_pool.hpp
- include/ylt/coro_io/detail/client_queue.hpp
- src/coro_io/tests/test_client_pool.cpp
The client pool won't collect connection when the free connection count greater than limitation, which may cause some performance problem in high concurrency.
Those connection will be keeped in a queue for short connection and they will be closed in 1 second default.
> [coro_io][feat] keep short connection.

- include/ylt/coro_io/client_pool.hpp
- src/coro_io/tests/test_client_pool.cpp
Sometimes the connection will timeout, so reconnection wait time should exclude the cost time of connection.
> [coro_io][feat] reconnect wait time now exclude connect cost time.

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
fix: make sure websocket read coroutine quit safely.
> [coro_http_client][fix]make ws_read coroutine quit safely

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
put ssl_stream in socket, to make sure it's lifetime is same with socket.
> [coro_http_client][fix]put ssl_stream in socket

- include/ylt/thirdparty/iguana/json_writer.hpp
- include/ylt/thirdparty/iguana/reflection.hpp
- include/ylt/thirdparty/iguana/xml_writer.hpp
- include/ylt/thirdparty/iguana/yaml_writer.hpp
- src/struct_json/examples/main.cpp
- src/struct_xml/examples/main.cpp
- src/struct_yaml/examples/main.cpp
support inner reflection:
```c++
class some_object {
int id;
public:
some_object() = default;
some_object(int i, std::string str) : id(i), name(str) {}
int get_id() const { return id; }
std::string get_name() const { return name; }
REFLECTION(some_object, id, name);
};
void test_inner_object() {
some_object obj{20, "tom"};
iguana::to_yaml(obj, str);
std::cout << str << "\n";
some_object obj1;
iguana::from_yaml(obj1, str);
assert(obj1.get_id() == 20);
assert(obj1.get_name() == "tom");
}
```
> [struct_json, struct_xml, struct_yaml][feat]inner reflection

- include/ylt/thirdparty/iguana/json_reader.hpp
- include/ylt/thirdparty/iguana/json_writer.hpp
- include/ylt/thirdparty/iguana/util.hpp
- include/ylt/thirdparty/iguana/xml_reader.hpp
- include/ylt/thirdparty/iguana/xml_writer.hpp
- include/ylt/thirdparty/iguana/yaml_reader.hpp
- include/ylt/thirdparty/iguana/yaml_writer.hpp
- src/struct_xml/examples/main.cpp
support smart pointer in struct.
```c++
struct shared_object {
std::shared_ptr<std::vector<std::shared_ptr<int>>> vec;
std::string b;
std::shared_ptr<int> c;
std::vector<std::shared_ptr<int>> d;
};
REFLECTION(shared_object, vec, b, c, d);
void test_sp() {
auto vec = std::make_shared<std::vector<std::shared_ptr<int>>>();
vec->push_back(std::make_unique<int>(42));
vec->push_back(std::make_unique<int>(21));
shared_object contents{std::move(vec),
"test",
std::make_shared<int>(24),
{std::make_shared<int>(1), std::make_shared<int>(4)}};
iguana::to_xml(contents, str);
shared_object cont;
iguana::from_xml(cont, str);  // throw exception.
std::cout << cont.b << "\n";
}
```
> [struct_xml, struct_json, struct_yaml][feat]support shared_ptr

- include/ylt/thirdparty/iguana/reflection.hpp
- src/struct_xml/examples/main.cpp
support reflect with  alias.
```c++
struct next_obj_t {
int x;
int y;
};
// struct alias name and fileds alias names.
REFLECTION_ALIAS(next_obj_t, "next", FLDALIAS(&next_obj_t::x, "w"),
FLDALIAS(&next_obj_t::y, "h"));
struct out_object {
std::unique_ptr<int> id;
std::string_view name;
next_obj_t obj;
REFLECTION_ALIAS(out_object, "qi", FLDALIAS(&out_object::id, "i"),
FLDALIAS(&out_object::name, "na"),
FLDALIAS(&out_object::obj, "obj"));
};
void test_alias() {
out_object m{std::make_unique<int>(20), "tom", {21, 42}};
std::string xml_str;
iguana::to_xml(m, xml_str);
std::cout << xml_str << "\n";
out_object m1;
iguana::from_xml(m1, xml_str);
assert(m1.name == "tom");
assert(m1.obj.x == 21);
assert(m1.obj.y == 42);
}
```
> [struct_json, struct_xml, struct_yaml][feat]support alias

- include/ylt/thirdparty/cinatra/time_util.hpp
- include/ylt/util/time_util.h
- src/util/tests/test_time_util.cpp
time_util::get_timestamp support string_view
> [util]support string_view

- include/ylt/easylog/record.hpp
- src/easylog/tests/test_easylog.cpp
support more types: bool, std::array<char, N>, object has data() or str(), tid etc.
```c++
char buf[5] = {"test"};
std::string_view sv = "test";
std::string str = "test";
std::array<char, 5> arr{"test"};
std::stringstream ss;
ss << "test";
ELOG_INFO << arr << ", " << ss;
auto id = std::this_thread::get_id();
ELOG_INFO << buf << ", " << str << ", " << sv << ", " << id;
```
> support more types

- include/ylt/coro_io/client_pool.hpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/examples/base_examples/server.cpp
The example client crash because we forget regist rpc function `nested_echo`. fix it.
> [coro_rpc][bugfix] fix example client

- include/ylt/easylog/appender.hpp
> [easylog][fix]fix lock

- include/ylt/easylog.hpp
- include/ylt/easylog/record.hpp
- src/easylog/tests/test_easylog.cpp
options:set get; support time;
> [easylog][feat]set get options

- include/ylt/easylog.hpp
- include/ylt/easylog/record.hpp
- src/easylog/tests/test_easylog.cpp
support fmt and std::format.
```c++
#if defined(HAS_FMT_LIB) || defined(HAS_STD_FORMAT)
ELOGFMT(INFO, "{} {}", 20, 42);
ELOGFMT(INFO, "it is a long string test {} {}", 42, "fmt");
#endif
```
> support fmt/std::format

- include/ylt/easylog/appender.hpp
- include/ylt/easylog/record.hpp
- src/easylog/tests/test_easylog.cpp
add more Severity to adapt other log lib; fix mac console color.
> [easylog][feat]add more Severity, fix mac console color

- include/ylt/easylog.hpp
- src/easylog/tests/test_easylog.cpp
- website/docs/zh/easylog/easylog_introduction.md
remove HAS_FMT_LIB and HAS_STD_FORMAT simplify usage.
```c++
// fmt::format/std::format stream
#if __has_include(<fmt/format.h>) || __has_include(<format>)
ELOGFMT(INFO, "easylog {}", 42);
#endif
```
> [easylog][improve]remove some define

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
replace unique_ptr<char[]> with std::string to optimize performance.
> [coro_http_client][improve]add simple buf instead of std::string

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
set body tail to \0;
use chunked_buf_ instead of read_buf_;
> [coro_http_client][fix]set tail to \0

- include/ylt/thirdparty/iguana/xml_reader.hpp
- src/struct_xml/examples/main.cpp
struct_xml::from_xml support string_view
> [struct-xml][feat]support sv

- include/ylt/thirdparty/cinatra/cinatra_log_wrapper.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- include/ylt/thirdparty/cinatra/http_parser.hpp
- include/ylt/thirdparty/cinatra/picohttpparser.h
- include/ylt/thirdparty/cinatra/utils.hpp
optimize: resp_headers to std::string_view;
fix handle_chunked;
> [coro_http_client][improve]update

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
fix: increase simple_buf size when read socket.
> [coro_http_client][fix]fix tail

- include/ylt/coro_io/io_context_pool.hpp
add size parameter: get_global_executor(pool_size);
> add size parameter

- include/ylt/easylog.hpp
- include/ylt/easylog/appender.hpp
- src/easylog/tests/test_easylog.cpp
Close #438 
```c++
ELOG(CRITICAL) same with ELOG(FATAL)
ELOG(WARN) same with ELOG(WARNING)
```
> treat the same with WARN/WARNING and CRITICAL/FATAL

- include/ylt/thirdparty/iguana/json_reader.hpp
- src/struct_json/examples/main.cpp
fix a bug in from_json.
```c++
struct person1 {
std::shared_ptr<std::string> name;
std::unique_ptr<int64_t> age;
};
REFLECTION(person1, name, age);
void use_smart_pointer() {
person1 p{std::make_shared<std::string>("tom"),
std::make_unique<int64_t>(42)};
iguana::to_json(p, str);
person1 p1;
iguana::from_json(p1, str); 
assert(*p1.name == "tom");
assert(*p1.age == 42);
}
```
> [struct_json][fix]fix json

- include/ylt/easylog.hpp
- include/ylt/easylog/appender.hpp
- include/ylt/easylog/record.hpp
- website/docs/zh/easylog/easylog_introduction.md
根据enum可以数值相等的特性，把等价的日志级别设为数值一致。然后可以减少对日志级别的判断
> [easylog] [improve]优化日志级别的使用

- src/easylog/tests/test_easylog.cpp
add ut for severity;
about #441 
```c++
CHECK(easylog::severity_str(easylog::Severity::WARN) ==
easylog::severity_str(easylog::Severity::WARNING));
CHECK(easylog::severity_str(easylog::Severity::CRITICAL) ==
easylog::severity_str(easylog::Severity::FATAL));
```
> [easylog][ut]add ut for easylog severity

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- website/docs/zh/coro_http_client/coro_http_client_introduction.md
support iostream/fstream.
```c++
auto result = co_await client_.async_upload_chunked(
str_url, coro_http::http_method::PUT, "test.xml",
coro_http::req_content_type::xml);
```
or
```c++
auto stream = std::make_shared<std::ifstream>("test.xml", std::ios::binary);
auto result = co_await client_.async_upload_chunked(
str_url, coro_http::http_method::PUT, stream,
coro_http::req_content_type::xml);
```
> [coro_http_client][feat]async_upload_chunked support iostream/filestream

- include/ylt/coro_http/coro_http_client.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_http/examples/example.cpp
support out buffer when request http.
```c++
void use_out_buf() {
using namespace coro_http;
str.resize(10);
std::string url = "http://cn.bing.com";
str.resize(6400);
coro_http_client client;
auto ret = client.async_request(url, http_method::GET, req_context<>{}, {},
std::span<char>{str.data(), str.size()});
auto result = async_simple::coro::syncAwait(ret);
bool ok = result.status == 200 || result.status == 301;
assert(ok);
std::string_view sv(str.data(), result.resp_body.size());
assert(result.resp_body == sv);
}
```
> [coro_http_client][feat]support out buf when request

- include/ylt/coro_io/io_context_pool.hpp
- src/coro_io/tests/test_corofile.cpp
implement missed virtual functions.
```c++
async_simple::coro::syncAwait(foo().via(coro_io::get_global_executor())); // will throw
```
> [coro_io][fix]add currentThreadInExecutor and currentContextId

- include/ylt/struct_pack/md5_constexpr.hpp
- include/ylt/struct_pack/reflection.hpp
- include/ylt/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_compile_time_calculate.cpp
Allow user add type id to distinct different c++ type with same struct_pack type by different hash.
Now user can defined a public static member `struct_pack_id`, this ID will be recorded in struct_pack type string to change hash code. This help user distinct different c++ type with same struct_pack type. User can also use this to avoid hash collision.
```cpp
struct foo_with_ID {
std::vector<int> a;
std::list<foo_with_ID> b;
constexpr static std::size_t struct_pack_id = 0;
};
struct foo {
std::vector<int> a;
std::list<foo> b;
};
static_assert(struct_pack::get_type_literal<foo_with_ID>()!=struct_pack::get_type_literal<foo>());
```
> [struct_pack][feat] add support for user_defined type id

- include/ylt/struct_pack.hpp
- include/ylt/struct_pack/reflection.hpp
- include/ylt/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/CMakeLists.txt
- src/struct_pack/tests/test_compile_time_calculate.cpp
- src/struct_pack/tests/test_derived.cpp
See #444 
Add function `struct_pack::deserialize_derived_class(...)`; this function can deserialize derived class to a unique_ptr of base class.
simple example:
```cpp
struct_pack::expected<std::unique_ptr<Base>,std::errc> ret = struct_pack::deserialize_derived_class<Base, foo, bar, gua>(sv);
```
```cpp
struct Base {
Base(){};
static struct_pack::expected<std::unique_ptr<Base>, struct_pack::errc>
deserialize(std::string_view sv);
virtual std::string get_name() const = 0;
virtual ~Base(){};
};
struct foo : public Base {
std::string hello = "1";
std::string hi = "2";
virtual std::string get_name() const override { return "foo"; }
friend bool operator==(const foo& a, const foo& b) {
return a.hello == b.hello && a.hi == b.hi;
}
};
STRUCT_PACK_REFL(foo, hello, hi);
struct foo2 : public Base { …
```
> [struct_pack][feat] support deserialize derived class

- include/ylt/struct_pack/struct_pack_impl.hpp
- src/struct_pack/tests/test_compile_time_calculate.cpp
- src/struct_pack/tests/test_data_struct.cpp
- src/struct_pack/tests/test_serialize.cpp
- website/docs/en/struct_pack/struct_pack_type_system.md
- website/docs/zh/struct_pack/struct_pack_type_system.md
They are outdated after we add layout info to trivial serialized type. 
remove concept of trivial_class_t/non_trivial_class_t
This code is legal now.
```cpp
struct person {
int age;
};
auto buffer = struct_pack::serialize(24, "Student"s);
struct_pack::deserialize<person>(buffer);
```
> [struct_pack] remove concept of trivial_class_t/non_trivial_class_t

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
> [coro_http_client][feat]add set get http headers

- include/ylt/thirdparty/cinatra/string_resize.hpp
resize compatible with gcc4.x(minimal version is gcc4.7.1) std::string, or gcc5 above with ```-D_GLIBCXX_USE_CXX11_ABI=0 ```
> [string_resize][fix]resize compatible with gcc4.x string

- include/ylt/coro_http/coro_http_server.hpp
- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_io/io_context_pool.hpp
- include/ylt/thirdparty/cinatra/coro_http_connection.hpp
- include/ylt/thirdparty/cinatra/coro_http_request.hpp
- include/ylt/thirdparty/cinatra/coro_http_response.hpp
- include/ylt/thirdparty/cinatra/coro_http_router.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
- include/ylt/thirdparty/cinatra/define.h
- include/ylt/thirdparty/cinatra/function_traits.hpp
- include/ylt/thirdparty/cinatra/http_parser.hpp
- include/ylt/thirdparty/cinatra/url_encode_decode.hpp
- include/ylt/thirdparty/cinatra/utils.hpp
- src/coro_http/examples/example.cpp
add new lib: coro_http_server
```c++
coro_http::coro_http_server server(1, 9001);
server.set_http_handler<coro_http::GET, coro_http::POST>(
"/", [](coro_http_request &req, coro_http_response &resp) {
// response in io thread.
resp.set_status_and_content(coro_http::status_type::ok, "hello world");
});
server.set_http_handler<coro_http::GET, coro_http::POST>(
"/coro",
[](coro_http_request &req,
coro_http_response &resp) -> async_simple::coro::Lazy<void> {
co_await coro_io::post([&]() {
// coroutine in other thread.
resp.set_status_and_content(coro_http::status_type::ok,
"hello world in coro");
});
});
server.sync_start();
```
> [new lib]coro_http_server

- include/ylt/coro_http/coro_http_server.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
coro_http_server: import more types.
coro_http_client: fix for checking; add an argument headers for async_get, async_post etc.
> [coro_http][fix and improve]do some update; add a check for client

- include/ylt/coro_io/rate_limiter.hpp
- src/coro_io/tests/CMakeLists.txt
- src/coro_io/tests/test_rate_limiter.cpp
Give a rate limiter implemented by async_simple. So that user can use RateLimiter in coroutine project.
coro_io::SmoothBurstyRateLimiter rateLimiter(10);
async_simple::coro::syncAwait(rateLimiter.acquire(1));
> [feature]add ratelimiter using async_simple coroutine

- include/ylt/coro_io/rate_limiter.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/struct_pack.hpp
- include/ylt/struct_pack/type_trait.hpp
- include/ylt/struct_pack/util.h
- src/struct_pack/examples/basic_usage.cpp
In old version, if struct_pack save binary to a container, it will call member function `resize()`. which cause useless initialization.
Add a helper function `struct_pack::detail::resize()`, which will resize some container(std::basic_string<char/unsigned char/signed char>, std::vector<char/unsigned char/signed char/std::byte>) without initialization.
Now struct_pack::serialize is faster:
old version:
```
struct_pack serialize 1 rect :            3 ns
struct_pack serialize 20 rects :          17 ns
struct_pack serialize 1 person :          11 ns
struct_pack serialize 20 persons :        110 ns
struct_pack serialize 1 monster :         76 ns
struct_pack serialize 20 monsters :       652 ns
```
new version:
```
struct_pack serialize 1 rect :            2 ns
struct_pack serialize 20 rects : …
```
> [struct_pack] enhance serialize performance by uninitialized resize

- include/ylt/coro_io/channel.hpp
Moving local variables as return value interferes with RVO.
This is a common bad practice.
> [coro_io]fix: std::move used on a local var as return value

- include/ylt/easylog.hpp
if statement within macro `ELOGV_IMPL`. `ELOGFMT_IMPL0` can be evaluated during compile-time.
I'm not 100% sure this change is proper, but it seems to me that `severity` should be compile-time constant as long as `Id` is used as one.
Macro definition `ELOGV_IMPL`. `ELOGFMT_IMPL0`, easylog.hpp
> [easylog]if statement can be constexpr

- README.md
- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_rpc/impl/context.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/coro_rpc/impl/coro_rpc_server.hpp
- include/ylt/coro_rpc/impl/router.hpp
- include/ylt/coro_rpc/impl/rpc_execute.hpp
- include/ylt/util/type_traits.h
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_router.cpp
- src/util/tests/test_meta_string.cpp
- website/docs/zh/coro_rpc/coro_rpc_doc.hpp
improve coro_io::post: handle exception;
rename type_traits namespace to uti.
fix typo;
> [coro_io][improve]Improve post

- include/ylt/coro_io/coro_file.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_io/examples/main.cpp
- src/coro_io/tests/test_corofile.cpp
improve coro_file performance: make sure fopen, fread, fwrite, fclose in the same thread, otherwise will cause poor performance.
support pread and pwrite.
```c++
coro_io::coro_file file{};
co_await file.async_open(filename.data(), coro_io::flags::read_write);
std::string str = "hello";
{
auto ec = co_await file.async_write(str.data(), str.size());
std::string result;
result.resize(10);
file.seek(0, SEEK_SET);
auto [rd_ec, size] = co_await file.async_read(result.data(), 5);
std::string_view s(result.data(), size);
CHECK(s == "hello");
}
```
pread pwrite example: linux and enable USE_PREAD_WRITE
```c++
#if defined(__GNUC__) and defined(USE_PREAD_WRITE)
coro_io::coro_file file{};
async_simple::coro::syncAwait(
file.async_open(filename.data(), coro_io::flags::read_write)); …
```
> [coro_file][improve]improve performance

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- include/ylt/thirdparty/cinatra/coro_http_connection.hpp
- include/ylt/thirdparty/cinatra/coro_http_request.hpp
- include/ylt/thirdparty/cinatra/coro_http_router.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
- include/ylt/thirdparty/cinatra/url_encode_decode.hpp
- include/ylt/thirdparty/cinatra/websocket.hpp
- include/ylt/thirdparty/cinatra/ws_define.h
- src/coro_http/examples/example.cpp
```
coro_http::coro_http_server server(1, 9001);
server.set_http_handler<cinatra::GET>(
"/ws_echo",
[](coro_http_request &req,
coro_http_response &resp) -> async_simple::coro::Lazy<void> {
assert(req.get_content_type() == content_type::websocket);
std::string out_str;
websocket_result result{};
while (!result.eof) {
result = co_await req.get_conn()->read_websocket();
if (result.ec) {
break;
}
if (result.type == ws_frame_type::WS_CLOSE_FRAME) {
std::cout << "close frame\n";
break;
}
out_str.append(result.data);
auto ec = co_await req.get_conn()->write_websocket(result.data);
if (ec) {
continue;
}
}
std::cout << out_str << "\n";
});
server.async_start();
```
> [coro_http][feat]coro_http_server support websocket

- include/ylt/struct_pack/unpacker.hpp
- include/ylt/struct_pack/util.h
add a hacker resize to enhance deserialize std::basic_string<POD>/std::vector<POD> speed.
Now when deserialize string/vector of pod, we won't init the memory when resize the container, which make deserialize faster.
> [struct_pack] improve performance when deserialize vector<pod>/string

- CMakeLists.txt
- cmake/install.cmake
related to issue : #505 
Make FetchContent available without any test or example target built
~~1. CMake version requirement is up ( 3.15 => 3.21)~~
2. Subdirectories will not add into project unless project is top-level .
3. Add some ```$<INSTALL_INTERFACE>``` and ```$<BUILD_INTERFACE>``` to avoid explicit call ```include_directories``` outside 
Simple testing used 
```
cmake_minimum_required(VERSION 3.21)
project(ylt_test)
include(FetchContent)
FetchContent_Declare(
yalantinglibs
GIT_REPOSITORY https://github.com/JYLeeLYJ/yalantinglibs.git
GIT_TAG feat/fetch # optional ( default master / main )
GIT_SHALLOW 1 # optional ( --depth=1 )
)
FetchContent_MakeAvailable(yalantinglibs)
add_executable(main main.cpp)
target_link_libraries(main yalantinglibs::yalantinglibs) …
```
> [CMake][feat] Support FetchContent use

- include/ylt/coro_rpc/impl/context.hpp
- include/ylt/coro_rpc/impl/coro_connection.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/examples/base_examples/rpc_service.cpp
- src/coro_rpc/examples/base_examples/rpc_service.h
- src/coro_rpc/examples/base_examples/server.cpp
- src/coro_rpc/tests/rpc_api.cpp
- src/coro_rpc/tests/rpc_api.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
Support attachment/close connection/get_connection_id by coro_rpc::context
```cpp
void echo_with_attachment(coro_rpc::context<void> conn) {
auto id=conn.get_connection_id();
std::cout<<"ID:<<id<<std::endl;
if (conn.get_request_attachment().empty()) {
conn.close();
}
std::string str = conn.release_request_attachment();
conn.set_response_attachment(std::move(str));
conn.response_msg();
}
```
> [coro_rpc] add attachment/close/get_connection_id for coro_rpc::context

- include/ylt/struct_pack/type_id.hpp
- website/docs/en/struct_pack/struct_pack_tips.md
- website/docs/zh/struct_pack/struct_pack_tips.md
std::bitset is hard to cross platform between big-endian & little-endian. 
Set it as unportable type now.
User can define marco STRUCT_PACK_ENABLE_UNPORTABLE_TYPE to enable std::bitset.
```cpp
#define STRUCT_PACK_ENABLE_UNPORTABLE_TYPE
#include<ylt/struct_pack.hpp>
int main() {
auto buffer = struct_pack::serialize(std::bitset<114>{});
return 0;
}
```
> [struct_pack][fix] set std::bitset as unportable type

- include/ylt/coro_io/coro_file.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
coro_http_server support cache static files;
coro_file support binary open for win;
> [coro_http][feat]update coro_http_server

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
sometimes when request timeout, need to check ec, operation abort error caused by timeout, should be timeout error.
> [coro_http_client][fix]correct ec

- include/ylt/thirdparty/iguana/define.h
- include/ylt/thirdparty/iguana/enum_reflection.hpp
- include/ylt/thirdparty/iguana/json_util.hpp
- include/ylt/thirdparty/iguana/reflection.hpp
- include/ylt/thirdparty/iguana/util.hpp
- include/ylt/thirdparty/iguana/xml_reader.hpp
- include/ylt/thirdparty/iguana/xml_util.hpp
- include/ylt/thirdparty/iguana/xml_writer.hpp
- include/ylt/thirdparty/iguana/yaml_reader.hpp
- include/ylt/thirdparty/iguana/yaml_util.hpp
- src/struct_xml/examples/main.cpp
Close #520 
```c++
struct some_object {
int id;
};
int main() {
std::string xml_str = R"(<some_object><id>20</id><name>小强</name></some_object>)";
some_object obj2;
iguana::from_xml(obj2, xml_str);
assert(obj2.id == 20);
assert(obj2.name == "小强");
}
```
> [strcut_xml][fix] fix parse Chinese text in xml

- include/ylt/struct_pack/type_id.hpp
- src/struct_pack/tests/test_data_struct2.cpp
The cross-platform problem of long type will be checkout by type hash, so don't need too worry about it.
Allow user serialize long type.
> [struct_pack] relax limitation for long type

- include/ylt/coro_rpc/impl/context.hpp
- include/ylt/coro_rpc/impl/coro_connection.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/coro_rpc/impl/coro_rpc_server.hpp
- include/ylt/coro_rpc/impl/errno.h
- include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
- include/ylt/coro_rpc/impl/router.hpp
- src/coro_io/tests/test_client_pool.cpp
- src/coro_rpc/benchmark/server.hpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/examples/base_examples/concurrent_clients.cpp
- src/coro_rpc/examples/base_examples/rpc_service.cpp
- src/coro_rpc/examples/base_examples/server.cpp
- src/coro_rpc/examples/file_transfer/file_client.cpp
- src/coro_rpc/examples/file_transfer/file_server.cpp
- src/coro_rpc/tests/ServerTester.hpp
- src/coro_rpc/tests/rpc_api.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_router.cpp
- website/docs/zh/coro_rpc/coro_rpc_doc.hpp
1. use enum class `coro_rpc::errc : uint8_t` instead of `std::errc` for cross-platform.
2. add support for user set error by coro_rpc::context<T>.
3. add support for user-defined framework error code.(It should between 100-255)
```cpp
void hello(coro_rpc::context<void> ctx) {
ctx.response_error(coro_rpc::errc::io_error,"This is io error.");
}
```
> [coro_rpc][breakchange] enhance error handling

- include/ylt/struct_pack/endian_wrapper.hpp
writer_bytes_array: function name error
decltype(t[0]) :t[0] may be return reference 
writer_bytes_array==>write_bytes_array
decltype(t[0]) ==>std::remove_reference_t<decltype(t[0])>
```
#include <iostream>
#include <random>
#include <string>
#include <type_traits>
#include <vector>
int main() {
std::string sz = "sss";
std::cout
<< std::is_same_v<
char,
std::remove_reference_t<decltype(
sz[0])>> << std::is_same_v<char, decltype(sz[0])> << std::endl;
std::vector<int> arr{1, 2};
std::cout
<< std::is_same_v<
int,
std::remove_reference_t<decltype(
arr[0])>> << std::is_same_v<int, decltype(arr[0])> << std::endl;
return 0;
}
10
10
```
> fix code error

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_http/examples/example.cpp
set sni host name as default.
```c++
std::string uri = "https://cn.bing.com";
[[maybe_unused]] auto ec = client.init_ssl("cn.bing.com"); // set sni host name.
auto data = co_await client.async_get(uri);
```
> [coro_http_client][improve]Improve ssl

- include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_http/examples/example.cpp
use empty asio buffer when readv will cause error on release model with clang, so avoid this.
> [coro_rpc]Fix for clang

- include/ylt/coro_io/coro_file.hpp
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- include/ylt/thirdparty/cinatra/coro_http_connection.hpp
- include/ylt/thirdparty/cinatra/coro_http_request.hpp
- include/ylt/thirdparty/cinatra/coro_http_router.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
- src/coro_http/examples/example.cpp
coro_http_server support multipart upload.
```c++
coro_http_server server(1, 8090);
server.set_http_handler<cinatra::PUT, cinatra::POST>(
"/multipart_upload",
[](coro_http_request &req,
coro_http_response &resp) -> async_simple::coro::Lazy<void> {
assert(req.get_content_type() == content_type::multipart);
auto boundary = req.get_boundary();
while (true) {
auto part_head = co_await req.get_conn()->read_part_head();
if (part_head.ec) {
co_return;
}
std::cout << part_head.name << "\n";
std::cout << part_head.filename << "\n";
std::shared_ptr<coro_io::coro_file> file;
std::string filename;
if (!part_head.filename.empty()) {
file = std::make_shared<coro_io::coro_file>();
filename = std::to_string(
std::chrono::system_clock::now().time_since_epoch().count());
size_t pos = …
```
> [coro_http_server][feat]Support multipart

- include/ylt/struct_pack/size_info.hpp
- include/ylt/struct_pack/user_helper.hpp
Closes #557 
1. fix size_info operator +
2. size_info now is in namespace struct_pack::detail
> [struct_paack][fix] fix size_info operator + & namespace

- include/ylt/thirdparty/cinatra/cookie.hpp
- include/ylt/thirdparty/cinatra/coro_http_connection.hpp
- include/ylt/thirdparty/cinatra/coro_http_request.hpp
- include/ylt/thirdparty/cinatra/coro_http_response.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
- include/ylt/thirdparty/cinatra/define.h
- include/ylt/thirdparty/cinatra/session.hpp
- include/ylt/thirdparty/cinatra/session_manager.hpp
- include/ylt/thirdparty/cinatra/utils.hpp
coro_http_server new feats:
- support cookie, session
- support http pipeline(GET/HEAD) request
- add more response content_type
> [coro_http_server][feat]update coro_http server

- include/ylt/thirdparty/iguana/detail/utf.hpp
- include/ylt/thirdparty/iguana/json_writer.hpp
- include/ylt/thirdparty/iguana/util.hpp
- include/ylt/thirdparty/iguana/yaml_writer.hpp
- src/struct_json/examples/main.cpp
#577 
support escape during serialization
```c++
#include <cassert>
#include <iostream>
#include "ylt/struct_json/json_reader.h"
#include "ylt/struct_json/json_writer.h"
struct person {
int age;
};
REFLECTION(person, name, age);
void test_escape_serialize() {
person p{"小\t强", 20};
std::string ss;
struct_json::to_json(p, ss);
std::cout << ss << std::endl;   \\ output:  {"name":"\u5C0F\t\u5F3A","age":20}
person p1;
struct_json::from_json(p1, ss);
assert(p1.name == p.name);
}
```
> [struct_json, struct_yaml][feat]support escape during serialization

- .github/workflows/code-coverage.yml
- .github/workflows/linux_llvm_cov.yml
> fix coverage

- .github/workflows/code-coverage.yml
- .github/workflows/linux_llvm_cov.yml
> [ci]test coverage

- .github/workflows/linux_llvm_cov.yml
- include/ylt/struct_pack/util.h
- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- include/ylt/thirdparty/cinatra/string_resize.hpp
fix resize because of a bug in gcc: https://stackoverflow.com/questions/76351500/unexpected-result-from-stdwstringresize-and-overwrite.
coro_http_client clear buffer when reset.
> [string_resize][bug]fix resize

- include/ylt/thirdparty/cinatra/coro_http_client.hpp
- src/coro_http/examples/example.cpp
add missed init_ssl logic when connect.
```c++
coro_http_client client{};
co_await client.connect("https://www.baidu.com");
result = co_await client.async_get("/");
assert(result.status == 200);
```
> [coro_http_client][bug]fix ssl

- include/ylt/coro_io/channel.hpp
- src/coro_io/tests/test_channel.cpp
support WRR(Weighted Round Robin)
```c++
auto hosts =
std::vector<std::string_view>{"127.0.0.1:8801", "127.0.0.1:8802"};
std::vector<int> weights{2, 1};
auto channel = coro_io::channel<coro_rpc::coro_rpc_client>::create(
hosts, {.lba = coro_io::load_blance_algorithm::WRR}, weights);
```
> [coro_io][feat]channel support WRR

- include/ylt/struct_pack/util.h
struct_pack_has_feature is not defined when compiling with project for c++23/gnu++2b or above.
Since struct pack is hpp header, we should consider suceefully compiling against standards above 20
Simply moved macro definition to outer scope
> [struct_pack][bugfix] fix undefined macro when compiling with standard greater than 20

- include/ylt/util/function_name.h
- src/coro_rpc/examples/base_examples/rpc_service.cpp
- src/coro_rpc/examples/base_examples/rpc_service.h
- src/coro_rpc/examples/base_examples/server.cpp
call rpc function which return bool failed when rpc server and rpc client are run at different OS(Windows,Linux).
close bug https://github.com/alibaba/yalantinglibs/issues/607
modify get_func_name function implement, when return string include windows function call style reference in [https://learn.microsoft.com/en-us/cpp/cpp/stdcall?view=msvc-170](url), remove the function call style string.
function get_func_name implement
> call coro_rpc function return bool failed crossplatform

- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_io/io_context_pool.hpp
- include/ylt/thirdparty/cinatra/coro_http_connection.hpp
- include/ylt/thirdparty/cinatra/coro_http_request.hpp
- include/ylt/thirdparty/cinatra/coro_http_response.hpp
- include/ylt/thirdparty/cinatra/coro_http_router.hpp
- include/ylt/thirdparty/cinatra/coro_http_server.hpp
- include/ylt/thirdparty/cinatra/coro_radix_tree.hpp
- include/ylt/thirdparty/cinatra/http_parser.hpp
- include/ylt/thirdparty/cinatra/picohttpparser.h
- src/coro_http/examples/example.cpp
- support coro_channel
- support set cpu affinity
- enable set response with multi buffer or not
- symplify redix tree
> [coro_http_server][feat]update http server

- include/ylt/coro_io/coro_io.hpp
- include/ylt/thirdparty/async_simple/MoveWrapper.h
- src/coro_http/examples/example.cpp
- src/coro_io/tests/CMakeLists.txt
- src/coro_io/tests/test_coro_channel.cpp
support select coroutine and coroutine channel.
similar with go and kotlin select.
```c++
async_simple::coro::Lazy<void> test_select_channel() {
auto channel = coro_io::create_channel<int>(1000);
co_await async_send(channel, 42);
auto lazy = coro_io::post([] {
});
int val3 = -1;
index = co_await select(std::pair{async_receive(channel),
[&](Try<std::pair<std::error_code, int>> result) {
val3 = result.value().second;
}},
std::pair{std::move(lazy), [&](Try<void>) {
val3 = 0;
}});
if (index == 0) {
CHECK(val3 == 42);
}
else if (index == 1) {
CHECK(val3 == 0);
}
}
```
> [coro_io][feat]support select coroutine

- include/ylt/struct_pack/derived_helper.hpp
- include/ylt/struct_pack/derived_marco.hpp
- src/struct_pack/tests/test_derived.cpp
Close #627 
The reason of this compile error is struct_pack::detail::is_base_class<derived1> returns true even though it is not the base class.
Add a deleted template function to stop the implicit type conversion can fix this problem.
> [struct_pack] fixed serialize std::unique_ptr<T> with T is derived class.

- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
avoid create timer every time when call rpc, to improve performance of coro_rpc_client.
make the timer as member variable.
> [coro_rpc_client][improve]avoid create timer everytime when call rpc

- include/ylt/coro_io/coro_io.hpp
- include/ylt/thirdparty/async_simple/coro/Collect.h
- src/coro_io/tests/test_coro_channel.cpp
```c++
void callback_lazy() {
using namespace async_simple::coro;
auto test0 = []() mutable -> Lazy<int> {
co_return 41;
};
auto test1 = []() mutable -> Lazy<int> {
co_return 42;
};
auto collectAnyLazy = [](auto&&... args) mutable -> Lazy<size_t> {
co_return co_await collectAny(std::move(args)...);
};
syncAwait(
collectAnyLazy(std::pair{test1(), [&](auto&& val) mutable -> Lazy<void> {
CHECK(val.value() == 42);
int r = co_await test0();
int result = r + val.value();
CHECK(result == 83);
}}));
std::vector<Lazy<int>> input;
input.push_back(test1());
auto index = syncAwait(collectAnyLazy(
std::move(input), [&test0](size_t index, auto val) mutable -> Lazy<void> {
CHECK(val.value() == 42);
int r = co_await test0();
int result = r + val.value();
CHECK(result == 83);
}));
CHECK(index == 0);
}
```
> [coro_io][feat]support lazy callback

- include/ylt/coro_rpc/impl/coro_rpc_server.hpp
- include/ylt/coro_rpc/impl/errno.h
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_rpc/tests/ServerTester.hpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
support set server address:
```cpp
coro_rpc_server server(1, 9001);
coro_rpc_server server(1, 9001, "0.0.0.0");
coro_rpc_server server(1, 9001, "127.0.0.1");
coro_rpc_server server(1, 9001, "localhost");
coro_rpc_server server(1, "0.0.0.0:9001");
coro_rpc_server server(1, "127.0.0.1:9001");
coro_rpc_server server(1, "localhost:9001");
```
> [coro_rpc/coro_http][feat]support set server address

- include/ylt/easylog/record.hpp
- src/easylog/tests/test_easylog.cpp
Add more restrict for data/str member, check if the return value can be appended to string or not.
> [easylog][fix]add more restrict for writing log with data/str

- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_io/io_context_pool.hpp
- include/ylt/coro_rpc/coro_rpc_context.hpp
- include/ylt/coro_rpc/impl/context.hpp
- include/ylt/coro_rpc/impl/coro_connection.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/coro_rpc/impl/coro_rpc_server.hpp
- include/ylt/coro_rpc/impl/errno.h
- include/ylt/coro_rpc/impl/expected.hpp
- include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
- include/ylt/coro_rpc/impl/router.hpp
- include/ylt/coro_rpc/impl/rpc_execute.hpp
- include/ylt/easylog/record.hpp
- src/coro_io/tests/test_coro_channel.cpp
- src/coro_rpc/benchmark/api/rpc_functions.hpp
- src/coro_rpc/benchmark/data_gen.cpp
- src/coro_rpc/benchmark/server.hpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/examples/base_examples/rpc_service.cpp
- src/coro_rpc/examples/base_examples/rpc_service.h
- src/coro_rpc/examples/base_examples/server.cpp
- src/coro_rpc/examples/file_transfer/rpc_service.cpp
- src/coro_rpc/tests/rpc_api.cpp
- src/coro_rpc/tests/rpc_api.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- src/coro_rpc/tests/test_router.cpp
- src/coro_rpc/tests/test_variadic.cpp
> [coro_rpc] simply rpc logic

- include/ylt/standalone/cinatra/coro_http_request.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- include/ylt/standalone/cinatra/http_parser.hpp
- src/coro_http/examples/example.cpp
- website/docs/zh/coro_http/coro_http_introduction.md
Close #654 
Close #655 
use std::error_code instead of std::errc for server.async_start/start;
init easylog singleton in server's construct function to make sure easylog life time is longer than server;
fix a bug of reverse proxy.
> [coro_http_server] use std::error_code instead of std::errc as result in coro_http_server. fix singleton servercrash when destructed.

- include/ylt/coro_io/client_pool.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_io/tests/test_client_pool.cpp
- src/coro_rpc/examples/base_examples/channel.cpp
- src/coro_rpc/examples/base_examples/client_pool.cpp
- src/coro_rpc/examples/base_examples/client_pools.cpp
- src/coro_rpc/examples/base_examples/concurrent_clients.cpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
There has some bug in old version client_pool.
1. the socket cost 100ms+ in connection may timeout util 60s.
2. the timer wont canceled if connection success in some case, which cost process blocking and wait for timeout.
1. fix client pool algorithm for slow connection and reduce latency.
2. fix the bug.
> [coro_io] fix client pool slow connect bug

- include/ylt/standalone/cinatra/coro_http_client.hpp
fix: use guard to make sure timer cancel when error occurred.
> [coro_http_client]fix timeout

- include/ylt/standalone/cinatra/coro_http_response.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
support http_response set http header span, avoid copy.
```cpp
for (auto &[k, v] : result.resp_headers) {
response.add_header(std::string(k), std::string(v));
}
```
to 
```cpp
response.add_header_span(result.resp_headers);
```
> [coro_http_server][feath]avoid copy headers

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_response.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_http/examples/example.cpp
- fix response content view
- coro_http_client tcp_no_delay as default
> [coro_http][fix]coro_http_client tcp_no_delay as default, fix response content view

- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_response.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_http/examples/example.cpp
fix build response with content view.
change function type default http hander to lazy type;
```cpp
server.set_http_handler<POST>(
"/view",
[](coro_http_request &req,
coro_http_response &resp) -> async_simple::coro::Lazy<void> {
resp.set_delay(true);
resp.set_status_and_content_view(status_type::ok,
req.get_body());  // no copy
co_await resp.get_conn()->reply();
});
```
> [coro_http_server]fix content_view

- include/ylt/standalone/iguana/detail/charconv.h
- include/ylt/standalone/iguana/detail/traits.hpp
- include/ylt/standalone/iguana/json_reader.hpp
- include/ylt/standalone/iguana/json_util.hpp
- include/ylt/standalone/iguana/json_writer.hpp
- include/ylt/standalone/iguana/reflection.hpp
- include/ylt/standalone/iguana/util.hpp
- include/ylt/standalone/iguana/version.hpp
- include/ylt/standalone/iguana/xml_reader.hpp
- include/ylt/standalone/iguana/xml_util.hpp
- include/ylt/standalone/iguana/xml_writer.hpp
- include/ylt/standalone/iguana/yaml_reader.hpp
Fix:
- struct_json parse double to int 
- struct_xml parse comments.
Features:
- struct_xml support escape and unescape.
- struct_json support std::variant
- struct_json support custom serialize float/double
- Add version.hpp for iguana
> [iguana]fix and update

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_request.hpp
- include/ylt/standalone/cinatra/multipart.hpp
- website/docs/zh/coro_http/coro_http_introduction.md
- fix: handle invalid multipart request;
- fix doc for rest api;
- remove some bench test code in coro_http_client;
- init is_websocket member variable;
> [coro_http]fix and update

- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_http/examples/example.cpp
if client set_ssl_schema(true), the url should add `https://` automatically.
```cpp
coro_http_client client4{};
client4.set_ssl_schema(true);
result = client4.get("www.baidu.com");
assert(result.status == 200);
coro_http_client client5{};
client5.set_ssl_schema(true);
co_await client5.connect("www.baidu.com");
result = co_await client5.async_get("/");
assert(result.status == 200);
```
> [coro_http_client][ifx]fix ssl option

- include/ylt/metric/metric.hpp
- include/ylt/standalone/cinatra/http_parser.hpp
- src/coro_http/examples/example.cpp
fix parse url queries
```cpp
http_parser parser{};
parser.parse_query("test");
parser.parse_query("test&a=42");
auto map = parser.queries();
assert(map.at("test")=="");
assert(map.at("a")=="42");
```
> [coro_http]fix parse url queries

- include/ylt/metric.hpp
- include/ylt/metric/counter.hpp
- include/ylt/metric/detail/ckms_quantiles.hpp
- include/ylt/metric/detail/time_window_quantiles.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/histogram.hpp
- include/ylt/metric/metric.hpp
- include/ylt/metric/summary.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- include/ylt/standalone/cinatra/metric_conf.hpp
- src/metric/tests/test_metric.cpp
- website/docs/zh/metric/metrict_introduction.md
some improvments:
- metric to json;
- remove metric;
- get metric by name and label
- labels for histgram and summary
> [metric][feat]improve metrics

- include/ylt/struct_pack/marco.h
MSVC intentionally defined `__cplusplus` to `199711L`, ignoring the actual standard, hence MACRO definitions of `SP_LIKELY` and `SP_UNLIKELY` go to wrong branches in MSVC build.
MSVC builds struct_pack with no [[likely]] attribute.
see [/Zc:__cplusplus](https://learn.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-170)
Just copied-pasted from iguana/Common.h
> fix: with MSVC, SP_LIKELY takes no effect

- include/ylt/metric/counter.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/histogram.hpp
- include/ylt/metric/metric.hpp
- include/ylt/metric/summary.hpp
- include/ylt/metric/system_metric.hpp
- src/metric/tests/test_metric.cpp
> add capacity of metrics

- include/ylt/metric/histogram.hpp
- src/metric/tests/test_metric.cpp
fix a bug: histogram output lack of labels name.
> [fix]fix output of histogram

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- src/coro_rpc/examples/base_examples/client.cpp
> [coro_rpc][fix] disable sso optimize in rpc client buffer, which may cause illegal address when user return value has std::string_view

- include/ylt/coro_rpc/impl/context.hpp
- include/ylt/coro_rpc/impl/coro_connection.hpp
- src/coro_rpc/examples/base_examples/channel.cpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/examples/base_examples/rpc_service.cpp
- src/coro_rpc/examples/base_examples/rpc_service.h
- src/coro_rpc/examples/base_examples/server.cpp
- src/coro_rpc/tests/rpc_api.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
- website/docs/en/coro_rpc/coro_rpc_client.md
- website/docs/en/coro_rpc/coro_rpc_server.md
- website/docs/zh/coro_rpc/coro_rpc_client.md
- website/docs/zh/coro_rpc/coro_rpc_server.md
1. fix example
2. add more document
3. add support for coro_rpc_server to set complete callback, When the server successfully writes the RPC response data to the socket, the  complete callback function is invoked. Users can set this callback function for logging, statistics, etc. Moreover, when the return value of the RPC function includes types like `std::string_view` or `std::span`, this callback function can be used to destruct objects at an appropriate time.
```cpp
void foo() {
auto ctx = coro_rpc::get_context();
ctx->set_response_handler([](const std::error_code& ec, std::size_t length) {
if (ec) {
std::cout << "error: " << ec.message() << std::endl;
} else {
std::cout << "ok: wrote " << length << " bytes" << std::endl;
}
});
return;
}
```
```cpp
std::string_view hello() {
auto ctx = …
```
> [coro_rpc][feature] support complete handler

- CMakeLists.txt
- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/version.hpp
out buffer is not an error, client will use inner buffer instead of out buffer when out buffer space is not enough.
> [coro_http_client][modify]update out buf logic

- include/ylt/coro_io/coro_io.hpp
> ignore SIGPIPE signal when use ::sendfile in linux

- include/ylt/standalone/cinatra/coro_http_client.hpp
fix a bug: don't clean out buffer after request.
> [coro_http_client]fix out buf

- website/docs/zh/struct_pack/struct_pack_intro.md
> [website] fix doc

- include/ylt/reflection/member_ptr.hpp
- include/ylt/reflection/user_reflect_macro.hpp
- src/reflection/tests/test_reflection.cpp
> [reflection][improve]for const object

- include/ylt/coro_io/channel.hpp
- include/ylt/coro_io/client_pool.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_io/tests/test_channel.cpp
now the work blance algorithm wont select unhealthy host unless all host are not alive.
add new client_pool config option `host_alive_detect_duration`, if it's zero, the detect will be disabled.
> [coro_io] add support for alive detect in client_pool

- include/ylt/metric/metric.hpp
- include/ylt/metric/system_metric.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- include/ylt/standalone/cinatra/metric_conf.hpp
- src/metric/tests/test_metric.cpp
- website/docs/zh/metric/metric_introduction.md
to solve static member init order problem.
> [metric][fix] replace static class with singleton

- BUILD.bazel
- include/ylt/coro_io/client_pool.hpp
- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_io/load_blancer.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_http/examples/CMakeLists.txt
- src/coro_http/examples/example.cpp
- src/coro_http/examples/load_blancer.cpp
- src/coro_io/tests/test_channel.cpp
- src/coro_io/tests/test_client_pool.cpp
- src/coro_io/tests/test_coro_channel.cpp
- src/coro_rpc/examples/base_examples/CMakeLists.txt
- src/coro_rpc/examples/base_examples/load_blancer.cpp
> [coro_io] rename channel to load_blancer, rename coro_channel to channel

- include/ylt/metric/counter.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/histogram.hpp
- include/ylt/metric/summary.hpp
- src/metric/tests/test_metric.cpp
fix: create summary with empty map will be as a default summary;
simplify: static label metric no need pass static label.
> [metric]Fix summary

- include/ylt/coro_io/detail/client_queue.hpp
- include/ylt/easylog/appender.hpp
- include/ylt/metric/summary.hpp
- include/ylt/util/concurrentqueue.h
- src/metric/tests/test_metric.cpp
> rename moodycamel namespace

- include/ylt/struct_pack/reflection.hpp
- include/ylt/struct_pack/type_calculate.hpp
- src/struct_pack/examples/serialize_config.cpp
- src/struct_pack/tests/test_type_info_config.cpp
- website/docs/en/struct_pack/struct_pack_tips.md
- website/docs/zh/struct_pack/struct_pack_tips.md
Now struct_pack support user-defined default global config 
```cpp
namespace struct_pack {
//default global config
constexpr sp_config set_default(sp_config*){ return sp_config::DISABLE_ALL_META_INFO; }
}
struct rect {
int a, b, c, d;
};
static_assert(struct_pack::get_needed_size(rect{}).size()==16);
```
> [struct_pack][feat] support user-define global config

- include/ylt/metric/counter.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/metric.hpp
- include/ylt/metric/metric_manager.hpp
- src/metric/tests/test_metric.cpp
add method: remove label, metric_manager to_json, label capacity;
fix compile for mac;
> [metric]Fix and improve

- include/ylt/metric/counter.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/summary.hpp
- src/metric/tests/test_metric.cpp
support serialize changed zero value.
> [metric][feat]serialize zero

- include/ylt/metric/detail/ckms_quantiles.hpp
don't return nan when empty summary.
> [metric][fix]remove nan

- include/ylt/reflection/member_count.hpp
- include/ylt/struct_pack/calculate_size.hpp
- include/ylt/struct_pack/packer.hpp
- include/ylt/struct_pack/reflection.hpp
- include/ylt/struct_pack/type_calculate.hpp
- include/ylt/struct_pack/type_id.hpp
- include/ylt/struct_pack/unpacker.hpp
> [struct_pack] fix reflection

- include/ylt/reflection/member_count.hpp
- include/ylt/reflection/member_names.hpp
- src/struct_xml/examples/main.cpp
get alias name by ADL
```cpp
struct point_t1 {
int x;
int y;
static constexpr auto get_alias_field_names(point_t1*) {
return std::array{field_alias_t{"X", 0}, field_alias_t{"Y", 1}};
}
static constexpr std::string_view get_alias_struct_name(point_t1*) {
return "point";
}
};
YLT_REFL(point_t1, x, y);
```
or 
```cpp
struct point_t1 {
int x;
int y;
};
YLT_REFL(point_t1, x, y);
inline constexpr auto get_alias_field_names(point_t1*) {
return std::array{field_alias_t{"X", 0}, field_alias_t{"Y", 1}};
}
inline constexpr std::string_view get_alias_struct_name(point_t1*) {
return "point";
}
```
> [reflection][change]get alias name by adl

- include/ylt/standalone/cinatra/coro_http_client.hpp
async_put forget handle the net error of server response, fix it.
> [coro_http][fix] fix handle result of async_upload

- CMakeLists.txt
- include/ylt/standalone/iguana/pb_reader.hpp
- include/ylt/version.hpp
- src/struct_pb/examples/main.cpp
- website/docs/zh/struct_pb/struct_pb_intro.md
improve performance:  we can memcpy a fixed type vector rather than push back one by one.
> [struct_pb]improve performance

- README.md
- cmake/install.cmake
when use  Cmake FetchContent  to import ylt, compile error:
**fatal error: iguana/json_reader.hpp: No such file or directory**
> fix Cmake FetchContent  build bug

- include/ylt/metric/counter.hpp
- include/ylt/metric/dynamic_metric.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/histogram.hpp
- include/ylt/metric/metric.hpp
- include/ylt/metric/metric_manager.hpp
- include/ylt/metric/summary.hpp
- include/ylt/metric/summary_impl.hpp
- include/ylt/metric/system_metric.hpp
- include/ylt/metric/thread_local_value.hpp
- src/metric/benchmark/bench.hpp
- src/metric/benchmark/main.cpp
- src/metric/tests/CMakeLists.txt
- src/metric/tests/parallel_test.cpp
- src/metric/tests/test_metric.cpp
1. refactor metric
2. add performance test & check it with asan
3. fix memory leak in summary in high concurrency read/write case
> [metric] refactor code

- include/ylt/metric/counter.hpp
- include/ylt/metric/summary.hpp
- src/metric/tests/parallel_test.cpp
- src/metric/tests/test_metric.cpp
> [metric] improve json serialize performance

- include/ylt/reflection/member_names.hpp
- include/ylt/reflection/member_value.hpp
- src/reflection/tests/test_reflection.cpp
- src/struct_pb/examples/main.cpp
> [reflection]Fix check cpp20

- include/ylt/reflection/member_names.hpp
- include/ylt/reflection/member_value.hpp
The purpose of this change is to ensure compatibility with different versions of the Microsoft Visual Studio (MSVC) compiler. The `_MSC_VER` macro is used to determine the compiler version, allowing the code to handle differences between Visual Studio 2019 (MSVC 14.2x) and Visual Studio 2022 (MSVC 14.30+). This is particularly important because VS2022 introduces full support for C++20 features, while earlier versions require a fallback implementation.
The code now includes conditional checks for `_MSC_VER`:
- When `_MSC_VER >= 1930` (Visual Studio 2022 or newer), the code leverages C++20 features such as generic lambdas and fold expressions.
- For older versions like VS2019 (`_MSC_VER >= 1920 && _MSC_VER < 1930`), the code falls back to an alternative implementation to maintain …
> [struct_json] is compatible with msvc versions

- include/ylt/metric/summary_impl.hpp
- src/metric/benchmark/bench.hpp
- src/metric/tests/parallel_test.cpp
- src/metric/tests/test_metric.cpp
1. metric now will refresh outdated data correctly.
2. avoid heap-use-after-free in some corner case, however, summary wont lazy collect memory.
> [metric] fix metric refresh logic

- coverage_gen.sh
- include/ylt/metric/metric.hpp
- src/metric/benchmark/bench.hpp
> [metric] fix metric ci 

- include/ylt/metric/counter.hpp
- include/ylt/metric/dynamic_metric.hpp
- include/ylt/metric/gauge.hpp
- include/ylt/metric/summary.hpp
- include/ylt/util/map_sharded.hpp
- src/metric/benchmark/bench.hpp
- src/metric/tests/parallel_test.cpp
> [metric] fix windows ci oom

- .github/workflows/linux_llvm_cov.yml
- include/ylt/standalone/iguana/detail/traits.hpp
- include/ylt/standalone/iguana/pb_util.hpp
- include/ylt/standalone/iguana/pb_writer.hpp
- include/ylt/standalone/iguana/util.hpp
- src/struct_pb/tests/main.cpp
to_pb support stream.
```cpp
my_space::inner_struct inner{41, 42, 43};
std::stringstream ss;
iguana::to_pb(inner, ss);
iguana::to_pb(inner, str);
```
> [struct_pb][feat]to_pb support stream

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_http/tests/CMakeLists.txt
- src/coro_http/tests/test_cinatra.cpp
> [coro_http][unit test]Add excption test

- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_http/tests/test_cinatra.cpp
> [coro_http][unit test]Test upload

- include/ylt/standalone/iguana/detail/traits.hpp
- include/ylt/standalone/iguana/json_reader.hpp
- include/ylt/standalone/iguana/pb_util.hpp
- include/ylt/standalone/iguana/util.hpp
- src/struct_json/examples/main.cpp
1. related issue: https://github.com/qicosmos/iguana/issues/332
2. struct_json support std::span;
> [struct_pb][bug]fix compile error

- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_http/tests/test_cinatra.cpp
fix the bug: 
- request ssl server ok;
- then reset client;
- request non ssl server failed, should be ok;
> [coro_http_client]fix reset

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- include/ylt/standalone/cinatra/define.h
- include/ylt/standalone/cinatra/http_parser.hpp
- src/coro_http/tests/test_cinatra.cpp
fix parse http body length, allow set the max http body len.
> [coro_http][fix]set max http body size

- include/ylt/reflection/member_value.hpp
- src/reflection/tests/test_reflection.cpp
add new index_of interface.
```cpp
struct simple {
int color;
int id;
int age;
};
auto i = index_of(&simple::id);
CHECK(i == 1);
i = index_of(&simple::age);
CHECK(i == 3);
```
> [reflection][feat]Add index of

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_router.hpp
- include/ylt/standalone/cinatra/session.hpp
- src/coro_http/tests/test_cinatra.cpp
- src/coro_http/tests/test_cinatra_websocket.cpp
http server support earlier response when multipart or chunked.
fix aspect;
add timeout checking for coro_http_client read_websocket.
> [coro_http][improve]support user response

- include/ylt/metric/dynamic_metric.hpp
- include/ylt/metric/histogram.hpp
- src/metric/tests/test_metric.cpp
> [metric][improve]Histgram label expire

- include/ylt/reflection/template_string.hpp
MSVC: Compiler Warning (level 4) C4127, conditional expression is constant.
```C++
struct TestReflected
{
int a;
};
constexpr auto name = ylt::reflection::get_struct_name<TestReflected>();
```
> [reflection][fix][msvc]: warning C4127

- include/ylt/metric/metric_manager.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_http/tests/test_cinatra.cpp
clear out buffer when async upload.
> [coro_http_client]fix async upload

- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- src/coro_http/tests/test_cinatra.cpp
- src/coro_http/tests/test_cinatra_websocket.cpp
- src/coro_http/tests/test_coro_http_server.cpp
support return socket available. close #859 
fix a test case.
> [coro_http][feat]support available

- include/ylt/reflection/template_string.hpp
- include/ylt/util/meta_string.hpp
- src/reflection/tests/test_reflection.cpp
Fixes https://github.com/alibaba/yalantinglibs/issues/872
raw_name = fixed length prefix + type_name + fixed length suffix
so we can get prefix_length and suffix_length first, then substr
but I'm wondering is this the right way, because the output is not exactly the same for all compilers,
on my win11:
clang:
* there is a space between int and &
* there is no **class** or **struct** for class name
```
CHECK(type_string<int&>() == "int &");
CHECK(type_string<int&&>() == "int &&");
CHECK(type_string<const int&>() == "const int &");
CHECK(type_string<const int&&>() == "const int &&");
CHECK(type_string<test_type_string::struct_test>() == "test_type_string::struct_test");
CHECK(type_string<test_type_string::struct_test&>() == "test_type_string::struct_test &"); …
```
> [reflection] fix type_string that lose const

- include/ylt/metric/summary_impl.hpp
- src/metric/benchmark/bench.hpp
- src/metric/tests/CMakeLists.txt
- src/metric/tests/parallel_test2.cpp
The old version summary has some bug, see #791 
We add stable test which asan could catch reproduce it in old version but works well in new version
> Add summary stable test

- include/ylt/metric/counter.hpp
- include/ylt/metric/summary_impl.hpp
- include/ylt/metric/system_metric.hpp
- src/metric/benchmark/bench.hpp
- src/metric/tests/test_metric.cpp
We found some possible data race in metric.
Fix possible data race
> [metric] fix data race

- include/ylt/metric/summary.hpp
> fix default max_age of summary

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- src/coro_rpc/examples/base_examples/client.cpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
> [coro_rpc] client support store response attachment data in external buffer

- .github/workflows/website.yml
Commit CI failed with the error message `Missing download info for actions/upload-artifact@v3`.
reason: https://github.com/orgs/community/discussions/142581
- `actions/configure-pages@v3 => actions/configure-pages@v4`
- `actions/upload-pages-artifact@v2 => actions/upload-pages-artifact@v3`
- `actions/deploy-pages@v2 => actions/deploy-pages@v4`
> [CI] Fix website CI

- include/ylt/coro_rpc/impl/common_service.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
fix: https://github.com/alibaba/yalantinglibs/issues/927
yalantinglibs\include\ylt\coro_rpc\impl\common_service.hpp(86,15): error C2665: “asio::ssl::context::use_certificate_chain_file”
yalantinglibs\include\ylt\coro_rpc\impl\common_service.hpp(95,15): error C2665: “asio::ssl::context::use_private_key_file”
yalantinglibs\include\ylt\coro_rpc\impl\common_service.hpp(104,15): error C2665: “asio::ssl::context::use_tmp_dh_file”
yalantinglibs\include\ylt\coro_rpc\impl\coro_rpc_client.hpp(539,18): error C2665: “asio::ssl::context::load_verify_file”
这几处调用时，std::filesystem::path 通过 string() 传参
最终在windows 上打开ssl 可以编译通过
> fix: windows ssl build

- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_rpc/impl/coro_connection.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/coro_rpc/impl/coro_rpc_server.hpp
- include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- src/coro_rpc/examples/base_examples/server.cpp
- src/coro_rpc/examples/user_defined_rpc_protocol/rest_rpc/config/rest_rpc_protocol.hpp
- src/coro_rpc/tests/test_coro_rpc_server.cpp
- website/docs/en/coro_rpc/coro_rpc_server.md
- website/docs/zh/coro_rpc/coro_rpc_server.md
1. support multi protocol (for example: start http server & rpc server in same address)
2. coro_rpc support big-endian platform.
This example add an http subserver for rpc server, we can support multi protocol now.
```cpp
coro_rpc_server server(/*thread=*/std::thread::hardware_concurrency(),
/*port=*/8801);
server.register_handler<echo>();
auto http_server = std::make_unique<coro_http::coro_http_server>(0, 0);
http_server->set_http_handler<coro_http::GET>(
"/", [](coro_http::coro_http_request& req,
coro_http::coro_http_response& resp) {
resp.set_status_and_content(coro_http::status_type::ok,
R"(<!DOCTYPE html>
<html>
<head>
<title>Example</title>
</head>
<body>
<p>This is an example of a simple HTML page with one paragraph.</p>
</body>
</html>)");
});
std::function dispatcher = …
```
> [coro_rpc] support multi protocol, support big-endian

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
Better display
Before:
the first endpoint is: 127.0.0.150052
After:
the first endpoint is: 127.0.0.1:50052
add ":" between host and port
> add separator charactor between host and port

- include/ylt/struct_pack/type_calculate.hpp
when building the tree using GCC-15, we have following warnings:
```
/home/kefu/dev/yalantinglibs/include/ylt/struct_pack/type_calculate.hpp: In function ‘constexpr decltype(auto) struct_pack::detail::get_size_literal()’:
/home/kefu/dev/yalantinglibs/include/ylt/struct_pack/type_calculate.hpp:64:58: warning: integer overflow in expression of type ‘int’ results in ‘-1321368961’ [-Woverflow]
64 |          static_cast<char>(size / (127 * 127 * 127 * 127 * 127) + 129)}};
|                                   ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
```
because `127` is an `int`, if the expression evaluates to an constant with cannot be represented with `int`, the compiler warns. in order to silence the warnings, let's use the `ull` prefix.
> [struct_pack] use unsigned long long integer literal to silence gcc warnings

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
rpc client support local ip:
```cpp
std::string local_ip = "192.168.0.1";
coro_rpc_client client(local_ip);
```
> [coro_rpc][feat]rpc client support local ip

- include/ylt/metric/dynamic_metric.hpp
- include/ylt/metric/metric_manager.hpp
- include/ylt/metric/system_metric.hpp
- src/metric/tests/test_metric.cpp
When I used `valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes` to perform memory leak detection, I found a report that there was 'still reachable' memory blocks in the ylt::metric. I resolved this issue
Change local static variable pointer to instance
```
==170047== 64 bytes in 1 blocks are still reachable in loss record 12 of 26
==170047==    at 0x4846FA3: operator new(unsigned long) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==170047==    by 0x333632: ylt::metric::dynamic_metric_manager<mqtt_metric_tag>::instance() (metric_manager.hpp:274)
==170047==    by 0x30B7C6: MqttExposer::init_mqtt_active_connections_metric() (MqttExposer.cpp:105)
==170047==    by 0x30AF71: MqttExposer::run() (MqttExposer.cpp:30)
==170047==    by 0x147E3C: main (main.cpp:14) …
```
> Fix valgrind 'still reachable' in metric

- include/ylt/coro_io/client_pool.hpp
- include/ylt/coro_io/coro_io.hpp
- include/ylt/coro_io/detail/client_queue.hpp
- include/ylt/coro_io/ibverbs/ib_buffer.hpp
- include/ylt/coro_io/ibverbs/ib_io.hpp
- include/ylt/coro_io/ibverbs/ib_socket.hpp
- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- src/coro_io/tests/ibverbs/test_ib_socket.cpp
- src/coro_rpc/benchmark/bench.cpp
- src/struct_pack/benchmark/CMakeLists.txt
client pool support connect reuse mode:
```cpp
auto ret =
co_await pool->send_request([&](coro_io::client_reuse_hint, coro_rpc::coro_rpc_client& client) {
return client.send_request_with_attachment<echo>(send_str_view);
});
if (ret.has_value()) {
auto result = co_await std::move(ret.value());
}
```
user could set `reuse_limit` in client_pool config. pipeline sending will be enabled if concurrency>reuse_limit. default value is -1, which means limit=24 in rdma mode or limit=160 in tcp mode.
> [coro_io][ibverbs] client pool/ibverbs support better client reuse

- include/ylt/coro_rpc/impl/coro_rpc_client.hpp
- src/coro_rpc/tests/test_coro_rpc_client.cpp
Fix const reference arguments for rpc client call.
> [coro_rpc_client]fix for rpc const ref arg

- include/ylt/coro_rpc/impl/coro_connection.hpp
- include/ylt/standalone/cinatra/coro_http_connection.hpp
- include/ylt/standalone/cinatra/picohttpparser.h
- src/coro_http/examples/chat_room.cpp
- src/coro_http/examples/client.html
Close #1044 
related: https://github.com/alibaba/yalantinglibs/discussions/1016
> [coro_http]Fix chat room

- include/ylt/metric/summary.hpp
- include/ylt/standalone/cinatra/coro_http_client.hpp
- include/ylt/standalone/cinatra/coro_http_server.hpp
- include/ylt/standalone/cinatra/define.h
- src/metric/tests/test_metric.cpp
1. fix dynamic summary `max_age` time for refresh data not work
2. set default summary `max_age` time as 0 seconds (never refresh)
3. add test
> [metric][coro_http] fix dynamic summary refresh & set default http body size to no limit

- include/ylt/metric/summary_impl.hpp
frontend_data_index_ may update by another thread, which may cause logic problem and return unexpected pointer.
add a local copy for index
> [metric][fix] summary may segment fault by visit nullptr ,fix summary_impl::get_data() to avoid load unexpected data array.
