include/struct_pack/struct_pack/reflection.h, include/struct_pack/struct_pack/struct_pack_impl.hpp
=> fix warning

include/struct_pack/struct_pack/struct_pack_impl.hpp
=> revert some

src/coro_rpc/examples/file_transfer/file_client/main.cpp, src/coro_rpc/examples/file_transfer/file_server/main.cpp, src/coro_rpc/examples/file_transfer/file_server/rpc_service.cpp, src/coro_rpc/examples/file_transfer/rpc_service/rpc_service.h
=> add download example

src/struct_pack/tests/test_serialize.cpp
It was caused by autocomplete.
=> remove useless header

src/coro_rpc/benchmark/client/client.cpp
Avoid compile error in latest asio.
=> avoid compile error when use latest asio

src/struct_pack/tests/test_tuplet.cpp
=> [struct_pack]fix compile error for arm

src/coro_rpc/doc/coro_rpc_introduction_cn.md
=> [no ci]adjust format

include/coro_rpc/coro_rpc/async_connection.hpp, include/coro_rpc/coro_rpc/async_rpc_server.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_server.hpp
Fix port in use for msvc; fix io_context life time.
=> Fix port and io context

include/coro_rpc/coro_rpc/coro_connection.hpp, src/coro_rpc/tests/test_variadic.cpp
change global server to local to avoid un-init server.
=> Improve test_variadic

include/coro_rpc/coro_rpc/async_rpc_server.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp
=> Adjust code format

include/coro_rpc/coro_rpc/coro_rpc_client.hpp
Simplify sync_call, reuse coroutine based call and connect method
=> sync_call and sync_connect reuse coroutine method

include/coro_rpc/coro_rpc/remote.hpp, include/coro_rpc/coro_rpc/router_impl.hpp, src/coro_rpc/CMakeLists.txt
output function name when debug.
=> add debug info: output function name

include/asio_util/asio_coro_util.hpp
User can resume the callback awaitor outside the callback, which is dangerous.
Add callback_handle as callback's parameter. User now should call the resume by the handler. So we can sure that the resume only happened in the callback.
```cpp
async_simple::Lazy<std::pair<std::error_code,size_t>> 
async_write_some(asio::stream_file& file,std::string_view my_buffer) {
asio_util::callback_awaitor<std::pair<std::error_code,size_t>> awaitor;
co_return co_await awaitor.await_resume([&](auto handler){
file.async_write_some(my_buffer, [&,=](std::error_code e, size_t n)
{
handler.set_value_then_resume(e,n);
});
});
}
```
=> [coro_rpc] Enhance callback_awaitor's safety

include/struct_pack/struct_pack.hpp, include/struct_pack/struct_pack/struct_pack_impl.hpp, src/coro_rpc/tests/ServerTester.hpp, src/struct_pack/tests/CMakeLists.txt, src/struct_pack/tests/test_serialize.cpp, src/struct_pack/tests/test_tuplet.cpp
Fix a array's hash calculate bug.
Add metainfo to struct_pack.
=> [struct_pack] Add metainfo

README.md, src/coro_rpc/doc/coro_rpc_introduction_cn.md, src/coro_rpc/doc/coro_rpc_introduction_en.md
add coro_rpc introduction English version
add coro_rpc introduction English version
doc
NA
=> add coro_rpc introduction_en.md

README.md, src/coro_rpc/doc/coro_rpc_introduction_en.md, src/struct_pack/doc/Introduction_CN.md, src/struct_pack/doc/Introduction_en.md
Add English version introduction of struct_pack 
NA
NA
=> add struct_pack introduction_en

include/coro_rpc/coro_rpc/remote.hpp
=> fix compile warning

include/struct_pack/struct_pack/struct_pack_impl.hpp
=> 修正vs2019 vc142工具编译错误

include/coro_rpc/coro_rpc/coro_rpc_client.hpp, src/coro_rpc/tests/ServerTester.hpp
=> debug to info

.github/workflows/linux_clang.yml, .github/workflows/linux_gcc.yml, .github/workflows/mac.yml, .github/workflows/windows.yml, include/coro_rpc/coro_rpc/async_connection.hpp, include/coro_rpc/coro_rpc/async_rpc_server.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/coro_rpc_server.hpp, src/coro_rpc/tests/ServerTester.hpp, src/coro_rpc/tests/inject_action.hpp, src/coro_rpc/tests/main.cpp, src/coro_rpc/tests/rpc_api.hpp, src/coro_rpc/tests/rpc_service.cpp, src/coro_rpc/tests/test_async_rpc_server.cpp, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_variadic.cpp
g_action not reset in some test case, so reset it in every test case. Will refactor injection later.
=> reset g_action

include/util/type_traits.h, src/util/tests/static_asserts.cpp
https://github.com/alibaba/yalantinglibs/issues/76
=> Add function_traits static_assert tests

src/coro_rpc/tests/test_async_rpc_server.cpp
Refactor test_async_rpc_server for debug
=> Refactor rpc test code 

include/coro_rpc/coro_rpc/async_connection.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, include/logging/easylog.hpp
Make log function print the caller filename and line.
=> improve log

include/struct_json/json_reader.h, src/struct_json/examples/main.cpp, thirdparty/iguana/iguana/error_code.h, thirdparty/iguana/iguana/json_reader.hpp, thirdparty/iguana/iguana/json_util.hpp, thirdparty/iguana/iguana/json_writer.hpp, thirdparty/iguana/iguana/prettify.hpp, thirdparty/iguana/iguana/reflection.hpp, thirdparty/iguana/iguana/value.hpp
update iguana to support json dom parse.
=> support json dom parse

src/coro_rpc/tests/CMakeLists.txt, src/coro_rpc/tests/test_async_rpc_server.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
Don't test outer_io_context to reduce test time.
=> don't test outer_io_context

src/coro_rpc/tests/ServerTester.hpp, src/coro_rpc/tests/test_async_rpc_server.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
=> improve logout

src/struct_pack/doc/struct_pack_layout_EN.md
add struct_pack memory layout md EN version
Doc
NA
=> add struct_pack layout EN version

src/struct_pack/doc/Introduction_CN.md, src/struct_pack/doc/Introduction_EN.md, src/struct_pack/doc/struct_pack_layout_EN.md, src/struct_pack/doc/struct_pack_type_system_CN.md
=> [struct_pack] update document

include/asio_util/asio_util.hpp, include/asio_util/io_context_pool.hpp, include/coro_rpc/coro_rpc/async_rpc_server.hpp, include/coro_rpc/coro_rpc/coro_rpc_server.hpp, src/coro_rpc/benchmark/api/rpc_functions.hpp, src/coro_rpc/tests/test_async_rpc_server.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
=> move to namespace

include/coro_rpc/coro_rpc/router.hpp, include/struct_pack/struct_pack/varint.hpp
=> fix header

include/coro_rpc/coro_rpc/async_connection.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/rpc_protocol.h, src/coro_rpc/tests/test_async_rpc_server.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_remote.cpp
=> add rpc header for response

src/struct_pack/doc/Introduction_EN.md, src/struct_pack/doc/struct_pack_layout_EN.md, src/struct_pack/doc/struct_pack_type_system_CN.md, src/struct_pack/doc/struct_pack_type_system_EN.md
=> add struct pack type system doc en

.github/workflows/mac.yml
brew install without update
see https://github.com/Homebrew/brew/issues/1670
=> fix mac ci

README.md
=> [no ci]update urls

.github/workflows/linux_clang.yml, .github/workflows/linux_gcc.yml, .github/workflows/mac.yml, cmake/struct_pb.cmake, src/struct_pb/conformance/absl/status/status.h, src/struct_pb/protoc-plugin/FileGenerator.cpp, src/struct_pb/protoc-plugin/StructGenerator.cpp, src/struct_pb/protoc-plugin/helpers.cpp, src/struct_pb/protoc-plugin/helpers.hpp, src/struct_pb/tests/helper.hpp
enable ci with protobuf
- fix build fail on protobuf 3.12
- run ci with protobuf
=> [struct_pb] protobuf 3.12 compat

include/util/meta_string.hpp, src/coro_rpc/tests/test_util.cpp
Add some useful functions in meta_string, will be used in easylog.
=> add some functions

include/coro_rpc/coro_rpc/rpc_execute.hpp, src/coro_rpc/examples/helloworld/client/main.cpp, src/coro_rpc/examples/helloworld/rpc_service/rpc_service.h, src/coro_rpc/examples/helloworld/server/main.cpp, src/coro_rpc/examples/helloworld/server/rpc_service.cpp
See #168 
Add more example for coro_rpc, fix typo.
=> [coro_rpc] Add more example, fix typo

include/easylog/easylog.h, include/easylog/record.hpp, src/coro_rpc/tests/rpc_service.cpp
=> [easylog]fix get thd id

src/easylog/benchmark/CMakeLists.txt, src/easylog/benchmark/main.cpp
=> [easy log]add benchmark

include/easylog/record.hpp
=> [easylog]minor improve

include/easylog/record.hpp
Add color for console log(warning above level)
=> add color for warn above severity

include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/rpc_execute.hpp, include/coro_rpc/coro_rpc/rpc_protocol.h, src/coro_rpc/benchmark/client/CMakeLists.txt, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_router.cpp
=> [coro_rpc] add_resp_err_code 

include/asio_util/asio_coro_util.hpp, include/asio_util/asio_util.hpp, src/coro_rpc/tests/test_coro_rpc_client.cpp
=> fix resolve

include/coro_rpc/coro_rpc/coro_rpc_client.hpp
=> [coro_rpc] Improve client close

include/asio_util/asio_coro_util.hpp, src/coro_rpc/examples/helloworld/server/rpc_service.cpp, src/coro_rpc/tests/test_coro_rpc_client.cpp, thirdparty/async_simple/async_simple/Executor.h
=> [coro_rpc]support co_await sleep

include/coro_rpc/coro_rpc/coro_rpc_client.hpp, src/coro_rpc/examples/helloworld/CMakeLists.txt, src/coro_rpc/examples/helloworld/concurrency_clients/main.cpp, src/coro_rpc/examples/helloworld/rpc_service/rpc_service.h, src/coro_rpc/examples/helloworld/server/main.cpp, src/coro_rpc/examples/helloworld/server/rpc_service.cpp
Add an demo to show how to run concurrency clients.
=> [coro_rpc] Add concurrency clients example

include/coro_rpc/coro_rpc/coro_rpc_client.hpp
=> [coro_rpc] fix client destructed in io thread

include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/rpc_protocol.h, src/coro_rpc/tests/test_coro_rpc_server.cpp
1. remove rpc_head's type hash code
2. add reserve field for rpc_head
=> [coro_rpc] remove rpc_head's type check

include/coro_rpc/coro_rpc/connection.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/default_config/struct_pack_protocol.hpp, include/coro_rpc/coro_rpc/router_impl.hpp, include/coro_rpc/coro_rpc/rpc_execute.hpp, include/coro_rpc/coro_rpc/rpc_protocol.h
=> [coro_rpc] allow user-defined serialize protocol in delay reply

include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/coro_rpc_server.hpp, include/coro_rpc/coro_rpc/rpc_protocol.h, src/coro_rpc/examples/helloworld/concurrency_clients/main.cpp, src/coro_rpc/examples/helloworld/rpc_service/rpc_service.h, src/coro_rpc/examples/helloworld/server/rpc_service.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
1. Add a constructor for server that constructed by struct server_config.
2. Move function id to req_head.
=> [coro_rpc] Move function id to req_head

include/coro_rpc/coro_rpc/coro_connection.hpp, include/coro_rpc/coro_rpc/coro_rpc_server.hpp, include/coro_rpc/coro_rpc/default_config/coro_rpc_config.hpp, include/coro_rpc/coro_rpc/default_config/coro_rpc_protocol.hpp, include/coro_rpc/coro_rpc/default_config/struct_pack_protocol.hpp, include/coro_rpc/coro_rpc/router.hpp, include/coro_rpc/coro_rpc/router_impl.hpp, include/coro_rpc/coro_rpc/rpc_execute.hpp, src/coro_rpc/tests/test_router.cpp
allow user-defined multi serialize protocol in same server.
=> [coro_rpc] allow aceecpt multi serialize protocol

include/easylog/easylog.h
support add more appenders, user can write log in more places.
=> [easylog]add appender

include/easylog/easylog.h, include/easylog/record.hpp, src/coro_rpc/CMakeLists.txt
=> check __cpp_lib_memory_resource

.github/workflows/linux_clang.yml, .github/workflows/linux_gcc.yml, .github/workflows/mac.yml, .github/workflows/windows.yml
eliminate github action warning 
see https://github.com/seanmiddleditch/gha-setup-ninja
- upgrade seanmiddleditch/gha-setup-ninja from v3 to master
=> upgrade seanmiddleditch/gha-setup-ninja from v3 to master

include/struct_pack/struct_pack/struct_pack_impl.hpp, src/coro_rpc/tests/ServerTester.hpp, src/coro_rpc/tests/rpc_service.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
=> [struct_pack] fix #207

include/coro_rpc/coro_rpc/coro_rpc_server.hpp
Remove the useless executor change when connection start.
=> [coro_rpc] remove useless executor

README.md, website/README.md
copy https://github.com/alibaba/yalantinglibs/issues/214#issuecomment-1436594293 to README
- add website build instruction
=> [no ci] update README, add website build instruction

gen_doc.sh, website/.vitepress/config.ts
Closes #214
changed:
1:delete the part of gen_sh.sh for fix style
2:modify themeConfig of the .vitepress/config.ts
attention:
this PR won't push the generate docs, only config changed are involved. so there have some conflicts of gen-docs.
It should be regenerated after merge.
=> fix: modify config.ts to fix zh page(alibaba#214) and cover(alibaba#218)

include/coro_rpc/coro_rpc/context.hpp, include/coro_rpc/coro_rpc/coro_rpc_client.hpp, include/coro_rpc/coro_rpc/default_config/coro_rpc_config.hpp, include/coro_rpc/coro_rpc/rpc_execute.hpp, include/coro_rpc/rpc_connection.hpp, src/coro_rpc/tests/rpc_api.hpp
=> [coro_rpc] add rpc_protocol for context

include/struct_pack/struct_pack/reflection.h, include/struct_pack/struct_pack/struct_pack_impl.hpp, src/struct_pack/tests/CMakeLists.txt, src/struct_pack/tests/test_compatible.cpp, src/struct_pack/tests/test_data_struct.cpp, src/struct_pack/tests/test_data_struct2.cpp
Fix compile error for recursive type.
=> [struct_pack] fix recursive data struct

include/struct_pack/struct_pack/struct_pack_impl.hpp, src/struct_pack/tests/test_compile_time_calculate.cpp, src/struct_pack/tests/test_data_struct.cpp, src/struct_pack/tests/test_tuplet.cpp
=> [struct_pack] fix some warning

src/coro_rpc/doc/coro_rpc_introduction_cn.md, src/coro_rpc/doc/coro_rpc_introduction_en.md
=> [coro_rpc] fix document

include/asio_util/asio_coro_util.hpp
allow user executor customize post op
=> [coro_rpc] allow user executor customize post op

include/coro_rpc/coro_rpc/coro_connection.hpp
Fix callback logic error for #244
=> [coro_rpc] fix callback logic error

README.md
=> [no ci]update readme

include/struct_pack/struct_pack/reflection.h, include/struct_pack/struct_pack/struct_pack_impl.hpp, src/struct_pack/tests/test_serialize.cpp
Add support for span
Now struct_pack support span. 
See test.
=> [struct_pack] Add support for span

include/struct_pack/struct_pack.hpp, include/struct_pack/struct_pack/reflection.h, include/struct_pack/struct_pack/struct_pack_impl.hpp, src/struct_pack/benchmark/msgpack_sample.hpp, src/struct_pack/benchmark/no_op.cpp, src/struct_pack/benchmark/no_op.h, src/struct_pack/benchmark/protobuf_sample.hpp, src/struct_pack/benchmark/struct_pack_sample.hpp, src/struct_pack/benchmark/struct_pb_sample.hpp
Speed up compile-time & reduce binary size
Limit some force inline use. It will be enable only when user define STRUCT_PACK_OPTIMIZE.
=> [struct_pack] limit force inline

.clang-format
=> [no ci] fix .clang-format

README.md, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/zh/guide/what_is_yalantinglibs.md
=> [no ci][doc] add Chinese readme

README.md, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/zh/guide/what_is_yalantinglibs.md
=> [no ci][doc] fix dead link

README.md, include/coro_http/coro_http_client.h, src/coro_http/examples/main.cpp, thirdparty/cinatra/cinatra/coro_http_client.hpp
=> update http client

include/asio_util/asio_coro_util.hpp, include/coro_rpc/coro_rpc/coro_connection.hpp, src/coro_http/CMakeLists.txt, src/coro_http/examples/main.cpp
update ssl macro for http client.
=> update ssl macro

thirdparty/iguana/iguana/detail/dragonbox_to_chars.h, thirdparty/iguana/iguana/error_code.h, thirdparty/iguana/iguana/json_reader.hpp, thirdparty/iguana/iguana/json_writer.hpp, thirdparty/iguana/iguana/reflection.hpp, thirdparty/iguana/iguana/type_traits.hpp, thirdparty/iguana/iguana/value.hpp, thirdparty/iguana/iguana/xml_reader.hpp, thirdparty/iguana/iguana/xml_writer.hpp
struct_json support std::string_view;
reflection support custom fields;
=> update struct_json and struct_xml

thirdparty/cinatra/cinatra/coro_http_client.hpp
=> coro_http] fix coro_http_client async_close memory leak

include/coro_http/coro_http_client.h, src/coro_http/examples/example.cpp, thirdparty/cinatra/cinatra/coro_http_client.hpp, thirdparty/cinatra/cinatra/define.h, thirdparty/cinatra/cinatra/utils.hpp
Update coro_http_client: add connect timeout config; export http_method;
=> update coro http

include/coro_io/client_pool.hpp, src/coro_http/examples/example.cpp, thirdparty/cinatra/cinatra/coro_http_client.hpp
add connect method, only connect to host, don't send http request.
=> connect to host

include/coro_http/coro_http_client.h
=> [no ci]export http_req_context

.github/workflows/ubuntu_clang.yml, .github/workflows/ubuntu_gcc.yml, include/coro_io/coro_file.hpp, src/coro_file/examples/main.cpp, src/coro_file/tests/test_corofile.cpp
Add more test cases and benchmark for coro_file.
=> test 100 files read and write

thirdparty/cinatra/cinatra/coro_http_client.hpp
fix http put: put empty body also need content length.
=> fix http put

include/coro_io/coro_file.hpp, src/coro_file/tests/test_corofile.cpp
coro_file support preemptive scheduling, multiple thread run one io_context.
=> support multithread one io_context

thirdparty/cinatra/cinatra/utils.hpp
=> add missed header

include/coro_io/channel.hpp, include/coro_io/client_pool.hpp, src/coro_http/examples/channel.cpp, src/coro_rpc/examples/channel/main.cpp, src/coro_rpc/examples/client_pools/main.cpp
=> use std::mutex to workaround gcc

include/coro_io/client_pool.hpp, src/coro_rpc/examples/client_pools/main.cpp
use shared_mutex instead of std::mutex
=> [coro_io] use std::shared_mutex

include/coro_io/coro_file.hpp, include/coro_io/io_context_pool.hpp, src/coro_file/examples/main.cpp, src/coro_file/tests/test_corofile.cpp, thirdparty/cinatra/cinatra/coro_http_client.hpp
=> [coro_io] add default ioc

thirdparty/cinatra/cinatra/coro_http_client.hpp
=> [coro_http] fix promise

include/coro_io/coro_file.hpp, thirdparty/cinatra/cinatra/coro_http_client.hpp
http client: send header and content use writev.
=> impromve request

include/coro_io/io_context_pool.hpp, src/coro_file/tests/test_corofile.cpp, thirdparty/cinatra/cinatra/coro_http_client.hpp
use coro_file when multipart upload; add multithread io_context pool;
=> improve multipart upload; add multithread context pool

thirdparty/cinatra/cinatra/coro_http_client.hpp
allow set chunked size; use alone io_context pool for chunked coro_file;
=> improve chunked upload

include/coro_http/coro_http_client.h, thirdparty/cinatra/cinatra/coro_http_client.hpp
coro_http client support string_view request(uri, body).
=> support sv

thirdparty/iguana/iguana/reflection.hpp
=> fix compile

thirdparty/cinatra/cinatra/coro_http_client.hpp
=> fix http client body

thirdparty/cinatra/cinatra/coro_http_client.hpp
Do some improvement for http_client, release_buf will return nullptr when content-len is 0;
=> improve when content-len is 0

include/coro_io/client_pool.hpp, include/coro_io/client_queue.hpp
=> [coro_io] fix idle timeout algorithm

src/coro_file/tests/test_corofile.cpp
add some test log for test_corofile.
=> add some logs

include/easylog/appender.hpp, include/easylog/easylog.h, include/easylog/record.hpp, src/easylog/benchmark/CMakeLists.txt, src/easylog/benchmark/main.cpp
optimize easylog performance, compare with spdlog, now it's faster than spdlog.
=> optimize performance of easylog

include/ylt/thirdparty/cinatra/utils.hpp
=> fix gmt time str

.github/workflows/mac.yml, .github/workflows/ubuntu_clang.yml, .github/workflows/ubuntu_gcc.yml, .github/workflows/windows.yml, website/.vitepress/config/en_data.ts, website/.vitepress/config/zh_data.ts
=> fix document, speed up ci.

include/ylt/struct_pack.hpp, website/Doxyfile, website/docs/zh/coro_rpc/coro_rpc_doc.hpp
=> [Doc] fix api reference

website/docs/zh/struct_pack/struct_pack_doc.hpp
=> [Doc] fix doc

include/ylt/coro_io/channel.hpp, include/ylt/coro_io/client_pool.hpp, src/coro_http/examples/channel.cpp, src/coro_rpc/examples/CMakeLists.txt, src/coro_rpc/examples/base_examples/channel.cpp
=> fix channel interface

include/ylt/coro_rpc/impl/coro_rpc_server.hpp
=> [coro_rpc] add get_io_context_pool() for server

include/ylt/coro_io/io_context_pool.hpp
fix: free pool when destructing.
=> free pool when destructing

src/coro_io/tests/test_corofile.cpp
Remove a case in coro_file test, sometimes it failed in some platform, will revert the case later.
=> Remove a case

.github/workflows/ubuntu_clang.yml, include/ylt/coro_io/channel.hpp, include/ylt/coro_io/client_pool.hpp, include/ylt/coro_io/detail/client_queue.hpp, include/ylt/coro_io/io_context_pool.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, src/coro_http/examples/channel.cpp, src/coro_io/tests/CMakeLists.txt, src/coro_io/tests/test_channel.cpp, src/coro_io/tests/test_client_pool.cpp, src/coro_rpc/benchmark/data_gen.cpp, src/coro_rpc/examples/base_examples/channel.cpp, src/coro_rpc/examples/base_examples/client_pool.cpp, src/coro_rpc/examples/base_examples/rpc_service.cpp, src/coro_rpc/tests/ServerTester.hpp, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_variadic.cpp
=> [coro_io] add test for coro_io

include/ylt/thirdparty/cinatra/coro_http_client.hpp, include/ylt/thirdparty/cinatra/picohttpparser.h
coro_http_client support request with path:
```c++
coro_http_client client;
co_await client.connect("purecpp.cn");
co_await client.async_get("/");
```
=> support request with path

include/ylt/thirdparty/cinatra/coro_http_client.hpp
=> ssl ctx to unique ptr

include/ylt/thirdparty/cinatra/coro_http_client.hpp
Fix bug in https://github.com/alibaba/yalantinglibs/pull/367
1. forget reset SNI_HOST_NAME in reset()
2. logic error cause each request with full path will reconnect the socket even the socket has connected.
fix bug
=> [coro_http] fix async_request reconnnect bug

include/ylt/coro_rpc/impl/coro_connection.hpp
clean code of the file `coro_connection.hpp`
1. remove forward declaration of `struct context_info_t`
2. remove useless comma of  `enum class rpc_call_type` 
3. use `{}` to initialize class member
`include/ylt/coro_rpc/impl/coro_connection.hpp`
=> [coro_rpc] clean code of the file "coro_connection.hpp"

website/docs/en/guide/what_is_yalantinglibs.md, website/docs/en/index.md, website/docs/en/struct_pack/struct_pack_tips.md, website/docs/zh/index.md, website/docs/zh/struct_pack/struct_pack_tips.md
=> [Doc] fix document

src/coro_http/examples/CMakeLists.txt, src/coro_io/examples/CMakeLists.txt, src/coro_io/tests/CMakeLists.txt, src/coro_rpc/benchmark/CMakeLists.txt, src/coro_rpc/examples/base_examples/CMakeLists.txt, src/coro_rpc/examples/file_transfer/CMakeLists.txt, src/coro_rpc/examples/user_defined_rpc_protocol/rest_rpc/CMakeLists.txt, src/coro_rpc/tests/CMakeLists.txt
=> [platform] support mingw-w64

include/ylt/thirdparty/cinatra/coro_http_client.hpp
use std::string instead of simple buffer(std::unique_ptr<char[]>).
=> [coro_http_client][improve]remove simple buffer

include/ylt/coro_io/client_pool.hpp, include/ylt/coro_io/coro_io.hpp, include/ylt/coro_io/detail/client_queue.hpp, include/ylt/coro_io/io_context_pool.hpp, include/ylt/util/meta_string.hpp, src/coro_io/tests/test_channel.cpp
=> [coro_io][feat][bugfix] enhance reconnect wait time & fix coro_io::sleep_for

README.md
Close #400 
dingtalk_group_number:645010455
=> [no ci]update dingtalk group id

include/ylt/thirdparty/cinatra/coro_http_client.hpp
use no exception interface;
reset ssl_stream when reset;
enable_tcp_no_delay;
=> [coro_http_client][fix]do some fix

include/ylt/coro_io/client_pool.hpp, include/ylt/easylog.hpp
=> [coro_io][feat] allow user override ELOG macro

include/ylt/coro_io/client_pool.hpp, src/coro_io/tests/test_client_pool.cpp
=> [coro_io] prevent promise no response in corner bug case.

README.md, src/easylog/tests/test_easylog.cpp, website/docs/en/index.md, website/docs/zh/easylog/easylog introduction.md, website/docs/zh/index.md
=> [easylog][doc]add doc for easylog

include/ylt/struct_pack/reflection.hpp, include/ylt/struct_pack/struct_pack_impl.hpp, src/struct_pack/examples/basic_usage.cpp, src/struct_pack/tests/test_data_struct.cpp, website/docs/en/struct_pack/struct_pack_type_system.md, website/docs/zh/struct_pack/struct_pack_type_system.md
=> [struct_pack][feat] support bitset

website/.vitepress/config/zh_data.ts, website/.vitepress/config/zh_locale.ts, website/docs/zh/coro_http_client/coro_http_client_introduction.md
=> [coro_http_client][doc]add doc for coro_http_client

include/ylt/thirdparty/cinatra/coro_http_client.hpp
fix: release_buf should also check chunked body.
=> [coro_http_client][fix] release buf

website/docs/zh/coro_http_client/coro_http_client_introduction.md
=> [coro_http_client][doc]update doc

include/ylt/thirdparty/cinatra/coro_http_client.hpp, include/ylt/thirdparty/cinatra/string_resize.hpp
=> [coro_http_client][improve]remove simple_buf

website/.vitepress/config/zh_data.ts, website/.vitepress/config/zh_locale.ts, website/docs/zh/index.md, website/docs/zh/struct_xxx/struct_xxx_introduction.md
add doc for struct_json struct_xml struct_json
=> add doc for struct_json struct_xml struct_json

include/ylt/easylog/appender.hpp
=> [easylog][fix] roll files

include/ylt/struct_pack.hpp, include/ylt/struct_pack/struct_pack_impl.hpp
simple interface of detail::get_types_code
=> [struct_pack] simple detail::get_types_code

include/ylt/coro_io/client_pool.hpp, src/coro_io/tests/test_client_pool.cpp
=> [coro_io] add more output to test

include/ylt/coro_http/coro_http_server.hpp
=> [coro_http_server][fix]add missed header

.github/workflows/ubuntu_clang.yml
fix ci for liburing case
use clang17
=> [ci]fix ci

include/ylt/coro_http/coro_http_client.hpp, include/ylt/thirdparty/cinatra/coro_http_client.hpp, src/coro_io/tests/test_client_pool.cpp
Reduce the size of resp_data #478 ;
Inherited enable_shared_from_this, websocket need it;
import more types;
=> [coro_http_client][improve]some improvment

src/coro_io/tests/test_rate_limiter.cpp
=> [coro_io][fix]fix ut for rate_limiter

include/ylt/coro_http/coro_http_client.hpp, include/ylt/coro_http/coro_http_server.hpp
simplified with namespace alias
=> [coro_http][improve]simplified with namespace alias

include/ylt/easylog/appender.hpp, include/ylt/easylog/record.hpp
Fix #491 : redundant log content.
Removed unnecessary code.
Some optimization in code style.
=> opti easylog

include/ylt/easylog.hpp
=> avoid redefine

README.md, include/ylt/struct_pack/calculate_size.hpp, include/ylt/struct_pack/packer.hpp, include/ylt/struct_pack/util.h, include/ylt/struct_pack/varint.hpp, src/struct_pack/benchmark/config.hpp, src/struct_pack/benchmark/data_def.hpp, src/struct_pack/benchmark/flatbuffer_sample.hpp, src/struct_pack/benchmark/protobuf_sample.hpp, src/struct_pack/benchmark/sample.hpp, src/struct_pack/benchmark/struct_pack_sample.hpp, src/struct_pack/benchmark/struct_pb_sample.hpp, src/struct_pack/examples/serialize_config.cpp, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/en/index.md, website/docs/en/struct_pack/struct_pack_tips.md, website/docs/zh/index.md, website/docs/zh/struct_pack/struct_pack_intro.md, website/docs/zh/struct_pack/struct_pack_tips.md
=> [struct_pack] add document, bench, example for fast_varint

include/ylt/easylog/record.hpp, include/ylt/util/time_util.h, src/util/tests/test_time_util.cpp
Close #507 
don't depend on cinatra, copy time_util into easylog.
=> [easylog][improve]make easylog independent

src/struct_pack/benchmark/benchmark.cpp, src/struct_pack/benchmark/config.hpp, src/struct_pack/benchmark/data_def.hpp, src/struct_pack/benchmark/flatbuffer_sample.hpp, src/struct_pack/benchmark/protobuf_sample.hpp, src/struct_pack/benchmark/struct_pack_sample.hpp, src/struct_pack/benchmark/struct_pb_sample.hpp
Add benchmark for zero-copy & varint for struct-pack.
=> [struct_pack] add benchmark for zero-copy & varint

include/ylt/thirdparty/cinatra/coro_http_connection.hpp, include/ylt/thirdparty/cinatra/coro_http_server.hpp, include/ylt/thirdparty/frozen/bits/pmh.h, include/ylt/thirdparty/frozen/random.h, include/ylt/thirdparty/iguana/detail/fast_float.h, src/coro_http/examples/CMakeLists.txt, src/coro_http/examples/chat_room.cpp, src/coro_http/examples/client.html
a html chat room, js as the client, coro_http_server as the server.
the chat room has such functions:
- list users
- update user list
- login
- logout
- send data
=> [coro_http][demo]add chat room demo

include/ylt/thirdparty/cinatra/coro_http_server.hpp, src/coro_http/examples/chat_room.cpp
=> use fs path

include/ylt/struct_pack/derived_marco.hpp, include/ylt/struct_pack/endian_wrapper.hpp, include/ylt/struct_pack/unpacker.hpp, include/ylt/struct_pack/util.h, src/struct_pack/tests/test_user_defined_type.cpp
=> [struct_pack][fix] fix bug of struct_pack::write

include/ylt/coro_rpc/impl/coro_connection.hpp, include/ylt/coro_rpc/impl/errno.h, include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp
=> [coro_rpc][breakchange] change err_code to 16bit

include/ylt/coro_rpc/impl/coro_rpc_server.hpp
=> [coro_rpc][fix] fix coro_rpc_server default constructor

include/ylt/struct_pack/unpacker.hpp, src/struct_pack/benchmark/benchmark.cpp, src/struct_pack/benchmark/config.hpp, src/struct_pack/benchmark/data_def.hpp, src/struct_pack/benchmark/flatbuffer_sample.hpp, src/struct_pack/benchmark/msgpack_sample.hpp, src/struct_pack/benchmark/protobuf_sample.hpp, src/struct_pack/benchmark/struct_pack_sample.hpp, src/struct_pack/benchmark/struct_pb_sample.hpp
benchmark result now is more accurate.
=> [struct_pack][fix] fix benchmark

include/ylt/struct_pack.hpp, include/ylt/struct_pack/compatible.hpp, include/ylt/struct_pack/error_code.hpp, include/ylt/struct_pack/md5_constexpr.hpp, include/ylt/struct_pack/trivial_view.hpp, website/Doxyfile, website/Doxyfile_cn, website/docs/en/struct_pack/struct_pack_intro.md, website/docs/zh/struct_pack/struct_pack_doc.hpp, website/docs/zh/struct_pack/struct_pack_intro.md, website/docs/zh/struct_pack/struct_pack_tips.md
Fix api document
The api document is broken and outdated. So fix it.
TODO: Fix en document.
=> [struct_pack][doc] fix cnapi document

include/ylt/struct_pack/util.h
=> [struct_pack][fix] fix undef macro __has_feature

website/docs/zh/coro_http/coro_http_introduction.md
fix a document error about collectAll.
=> [no ci] fix doc

website/.vitepress/config/zh_data.ts
=> [no ci]fix doc link

include/ylt/thirdparty/cinatra/coro_http_client.hpp, include/ylt/thirdparty/cinatra/coro_http_connection.hpp, include/ylt/thirdparty/cinatra/define.h, include/ylt/thirdparty/cinatra/url_encode_decode.hpp, include/ylt/thirdparty/cinatra/utils.hpp, include/ylt/thirdparty/cinatra/websocket.hpp, src/coro_http/examples/example.cpp
- remove some unused code
- improve websocket example
- fix a bug of websocket: missed ping/pong payload
- improve: set shrink memory to response
=> [coro_http]update and fix

include/ylt/coro_io/channel.hpp
=> [coro_io] add size() for channel

.github/workflows/linux_llvm_cov.yml, coverage_gen.sh, include/ylt/thirdparty/cinatra/coro_http_client.hpp, include/ylt/thirdparty/cinatra/coro_http_response.hpp, src/coro_http/examples/example.cpp
coro_http_server support gzip.
=> [coro_http_server][feat]support gzip

README.md, website/docs/zh/guide/what_is_yalantinglibs.md
=> [no ci][doc] fix tab

include/ylt/coro_io/channel.hpp, include/ylt/coro_io/client_pool.hpp
=> [coro_io] add size() for channel/client_pool

include/ylt/easylog.hpp, src/easylog/tests/test_easylog.cpp
=> [easylog][fix]allow single arg for fmt/std::format

CMakeLists.txt, cmake/install.cmake
=> Release v0.3.1

cmake/install.cmake
=> fix install by package manager

include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp
set tcp no_delay for client and server.
=> [coro_rpc][improve]set tcp nodelay

.github/workflows/ubuntu_gcc.yml, cmake/develop.cmake
try to fix asan problem for gcc.
=> [ci][gcc asan]test gcc asan in ubuntu20.04

README.md, include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_router.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, include/ylt/standalone/cinatra/websocket.hpp, src/coro_http/examples/example.cpp, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/zh/coro_http/coro_http_introduction.md, website/docs/zh/guide/what_is_yalantinglibs.md
- Remove coro_http_server web socket callback
- coro_http_server set default http handler
- coro_http_server support reverse websocket proxy
- Fix http client web socket: mask always
- Fix chunked
- Update documents
=> [coro_http][fix][feature]coro_http

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_request.hpp, include/ylt/standalone/cinatra/coro_http_response.hpp, include/ylt/standalone/cinatra/gzip.hpp, include/ylt/standalone/cinatra/utils.hpp, include/ylt/standalone/cinatra/websocket.hpp, src/coro_http/examples/example.cpp
fix: remove some static local 
feat: support websocket deflate, relate with #527
=> [coro_http][fix][feat]fix and support ws deflate

CMakeLists.txt, include/ylt/version.hpp
add version.hpp to show current version information, it will be updated when release a new ylt version.
=> [ylt]Add version

include/ylt/standalone/cinatra/coro_http_client.hpp
revert some code: conn_timeout_duration_ to req_timeout_duration_
=> [coro_http_client]revert some code

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_router.hpp, include/ylt/standalone/cinatra/coro_radix_tree.hpp, include/ylt/standalone/cinatra/http_parser.hpp, include/ylt/standalone/cinatra/picohttpparser.h, include/ylt/standalone/cinatra/version.hpp, include/ylt/standalone/cinatra/websocket.hpp
- fix websocket parser;
- fix queries: clear last queries;
- simplify some code in websocket; 
- add version.hpp for cinatra;
=> [coro_http_server]fix and improve

cmake/config.cmake, include/ylt/coro_rpc/impl/context.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/coro_rpc/impl/default_config/coro_rpc_config.hpp, src/coro_io/tests/test_channel.cpp, src/coro_io/tests/test_client_pool.cpp, src/coro_rpc/benchmark/data_gen.cpp, src/coro_rpc/examples/base_examples/rpc_service.cpp, src/coro_rpc/examples/base_examples/server.cpp, src/coro_rpc/examples/file_transfer/rpc_service.cpp, src/coro_rpc/tests/rpc_api.cpp, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_variadic.cpp, website/Doxyfile, website/Doxyfile_cn, website/docs/en/coro_rpc/coro_rpc_client.md, website/docs/en/coro_rpc/coro_rpc_introduction.md, website/docs/en/coro_rpc/coro_rpc_server.md, website/docs/zh/coro_rpc/coro_rpc_client.md, website/docs/zh/coro_rpc/coro_rpc_introduction.md, website/docs/zh/coro_rpc/coro_rpc_server.md
=> [doc] add coro_rpc doc

include/ylt/easylog/appender.hpp
=> [easylog] fix last_tid

include/ylt/easylog.hpp
=> 修改MELOG_TRACE宏定义 

include/ylt/coro_io/io_context_pool.hpp, include/ylt/metric.hpp, include/ylt/metric/counter.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/histogram.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/summary.hpp, include/ylt/metric/system_metric.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, src/metric/tests/test_metric.cpp, website/docs/zh/metric/metrict_introduction.md
- add system metrics: cpu, memory, io, avg load, metrics statistic.
- fix a bug of serialize metric
=> [metric][feat and fix]add inner metrics

include/ylt/coro_io/coro_file.hpp, include/ylt/coro_io/coro_io.hpp, include/ylt/standalone/cinatra/brzip.hpp, include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_request.hpp, include/ylt/standalone/cinatra/coro_http_response.hpp, include/ylt/standalone/cinatra/define.h, include/ylt/standalone/cinatra/response_cv.hpp, include/ylt/standalone/cinatra/utils.hpp, include/ylt/standalone/cinatra/websocket.hpp, src/coro_http/examples/example.cpp, website/docs/zh/coro_http/coro_http_introduction.md
- support send file without copy by linux send file api;
- support br uncompress
=> [coro_http_client][feat]async upload file no copy

CMakeLists.txt, include/ylt/coro_io/coro_file.hpp, include/ylt/standalone/cinatra/coro_http_client.hpp
=> [coro_http][fix] fix client upload file which filename is string_view

.github/workflows/website.yml, website/docs/zh/metric/metrict_introduction.md
=> [website]fix doc format

include/ylt/coro_io/coro_io.hpp, include/ylt/standalone/cinatra/coro_http_client.hpp
=> [coro_http][coro_io][fix]correct close client when sendfile error

include/ylt/coro_io/channel.hpp
=> [coro_io][fix] init random seed for RandomLoadBlancer

include/ylt/coro_io/client_pool.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/standalone/cinatra/coro_http_client.hpp
=> [coro_rpc][coro_http] set default timeout duration as 30s

include/ylt/metric/counter.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/histogram.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/summary.hpp, include/ylt/metric/system_metric.hpp, include/ylt/metric/thread_local_value.hpp, src/metric/tests/test_metric.cpp
replace atomic with thread local to improve performance.
=> [metric][feat]Improve counter

include/ylt/metric/counter.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/system_metric.hpp, include/ylt/metric/thread_local_value.hpp
=> [metric][fix]System metric

include/ylt/coro_io/load_blancer.hpp
=> [no ci][coro_io] fix rename

include/ylt/standalone/cinatra/coro_http_client.hpp
=> [breakchange][feat] async_upload support offset

include/ylt/struct_pack/reflection.hpp
=> [struct_pack][fix] fix compile error in msvc

include/ylt/metric/counter.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/metric_manager.hpp, include/ylt/metric/system_metric.hpp, include/ylt/metric/thread_local_value.hpp, src/metric/tests/test_metric.cpp
1. filter options support label value;
2. support clean expired labels;
=> [metric][feat]Improve metric some

include/ylt/standalone/cinatra/coro_http_client.hpp
fix: chunked and multipart also clean out buf
=> [coro_http_client][fix]chunked and multipart also clean out buf

include/ylt/easylog/record.hpp
=> [easylog][fix] fix compile error in freeBSD

include/ylt/metric/counter.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/metric_manager.hpp, include/ylt/metric/system_metric.hpp
fix metric_manger singleton life time.
=> [metric]fix stat system metric

include/ylt/easylog/record.hpp
=> [struct_pack][fix] fix freebsd

include/ylt/metric/counter.hpp, include/ylt/metric/thread_local_value.hpp, src/metric/benchmark/CMakeLists.txt, src/metric/benchmark/main.cpp
add benchmark for counter;
fix a bug of thread local;
=> [metric][bench and fix]add bench and fix

include/ylt/metric/counter.hpp, include/ylt/metric/detail/ckms_quantiles.hpp, include/ylt/metric/detail/time_window_quantiles.hpp, include/ylt/metric/gauge.hpp, include/ylt/metric/histogram.hpp, include/ylt/metric/summary.hpp
reduce memory occupy for summary.
=> [metric]Optimize summary

include/ylt/metric/summary.hpp
avoid visit destructed members of summary.
=> [metric]fix life time

include/ylt/reflection/member_names.hpp, include/ylt/reflection/member_value.hpp, include/ylt/reflection/user_reflect_macro.hpp, src/reflection/tests/test_reflection.cpp, src/struct_xml/examples/main.cpp
fix function call;
fix reflect private members;
simplify alias field;
=> [reflection]fix and improve

include/ylt/metric/summary_impl.hpp, src/metric/tests/test_metric.cpp
=> [metric] fix summary

include/ylt/metric/summary.hpp
=> [metric] fix summary serialize to json thread-safe

include/ylt/standalone/iguana/dynamic.hpp, include/ylt/standalone/iguana/json_writer.hpp, include/ylt/standalone/iguana/util.hpp
=> [struct_json][feat]support custom optional(struct_pack compatible)

include/ylt/metric/dynamic_metric.hpp, include/ylt/metric/metric_manager.hpp, include/ylt/metric/thread_local_value.hpp, include/ylt/util/map_sharded.hpp, src/metric/benchmark/bench.hpp, src/metric/benchmark/main.cpp, src/metric/tests/parallel_test.cpp
=> [metric] use sharded map for better parallel performance

.github/workflows/linux_llvm_cov.yml, include/ylt/metric/dynamic_metric.hpp
=> [metric] add code coverage ci

.github/workflows/linux_llvm_cov.yml, include/ylt/standalone/iguana/pb_writer.hpp, src/reflection/tests/test_reflection.cpp, src/struct_pb/tests/main.cpp, website/docs/zh/reflection/reflection_introduction.md, website/docs/zh/struct_pb/struct_pb_intro.md
fix type string;
fix doc;
fix ci coverage;
simplify _ylts;
=> [struct_pb]fix type, fix doc

.github/workflows/clang-format.yml, .github/workflows/clean_cache.yml, .github/workflows/linux_llvm_cov.yml, .github/workflows/mac.yml, .github/workflows/s390x.yml, .github/workflows/ubuntu_clang.yml, .github/workflows/ubuntu_gcc.yml, .github/workflows/website.yml, .github/workflows/windows.yml, coverage_gen.sh
=> [ci] fix code coverage

include/ylt/metric/dynamic_metric.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/system_metric.hpp
=> 移动 g_user_metric_label_count位置，避免循环引用

src/easylog/tests/test_easylog.cpp
=> [ci]fix upload cov files

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_cinatra_websocket.cpp
=> [coro_http]Add some test

include/ylt/standalone/cinatra/coro_http_client.hpp
refactor upload file, remove duplicate code.
=> [coro_http][refactor]begin to refactor

include/ylt/metric/summary_impl.hpp, include/ylt/standalone/cinatra/gzip.hpp, include/ylt/standalone/cinatra/multipart.hpp, include/ylt/standalone/cinatra/picohttpparser.h, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_cinatra_websocket.cpp
remove some unused function and variable.
=> [coro_http][clean code]remove some unused

include/ylt/standalone/cinatra/coro_http_client.hpp, src/coro_http/tests/test_cinatra.cpp
=> [coro_http][unit test]fix and test

include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, src/coro_http/tests/CMakeLists.txt, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_coro_http_server.cpp
add tests for coro_http_server
=> [coro_http][ut]add tests

include/ylt/metric/counter.hpp, include/ylt/metric/histogram.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/metric_manager.hpp, include/ylt/util/map_sharded.hpp, src/metric/tests/test_metric.cpp
=> [metric][unit test]Fix and test metric

include/ylt/metric/metric_manager.hpp, src/metric/tests/test_metric.cpp
=> [metric][fix]to_json for empty vector

src/struct_pb/tools/proto_to_struct.cpp, src/struct_pb/tools/struct_code_generator.hpp, src/struct_pb/tools/struct_token.hpp
For close iguana [issue 330](https://github.com/qicosmos/iguana/issues/330)
proto file to struct pack nested message support and add namespace.
=> [struct_pb] add namespace and nested message generator

.github/workflows/mac.yml, include/ylt/coro_io/io_context_pool.hpp, src/coro_io/tests/test_client_pool.cpp
=> [ci]fix mac ci

include/ylt/coro_rpc/impl/common_service.hpp, include/ylt/coro_rpc/impl/context.hpp, include/ylt/coro_rpc/impl/coro_connection.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp, include/ylt/coro_rpc/impl/router.hpp
change printf log to stream log.
=> [coro_rpc][log]use stream log

include/ylt/coro_io/load_blancer.hpp
=> fix load_blancer move assign operator

include/ylt/metric/summary.hpp, include/ylt/metric/summary_impl.hpp, src/metric/tests/test_metric.cpp, website/docs/zh/metric/metric_introduction.md
=> add support for uint64 bucket element type for summary.

.github/actions/coverage/action.yml
remove some third-party file in code coverage
=> [ci] update code coverage

include/ylt/standalone/cinatra/coro_http_client.hpp, src/coro_http/examples/example.cpp
clear outbuf when async upload.
=> [coro_http_client]fix async upload

include/ylt/thirdparty/async_simple/coro/SpinLock.h
=> fix async-simple no discard when call spinlock::coScopedLock

include/ylt/standalone/cinatra/coro_http_client.hpp
default will timeout;
if timeout less than 0, won't timeout;
=> [coro_http_client]improve timeout

include/ylt/coro_io/coro_io.hpp, include/ylt/coro_io/io_context_pool.hpp, include/ylt/metric/summary_impl.hpp, include/ylt/thirdparty/async_simple/Signal.h, include/ylt/thirdparty/async_simple/coro/Collect.h, include/ylt/thirdparty/async_simple/coro/CountEvent.h, src/coro_io/tests/CMakeLists.txt, src/coro_io/tests/test_cancel.cpp, src/coro_io/tests/test_client_pool.cpp, src/coro_io/tests/test_coro_channel.cpp, src/coro_rpc/examples/base_examples/client_pool.cpp, src/coro_rpc/examples/base_examples/concurrent_clients.cpp
=> [coro_io] add support for cancellation

include/ylt/coro_rpc/impl/coro_rpc_server.hpp
We found some data race in coro_rpc
fix data race
=> [coro_rpc] fix ELOG data race in coro_rpc::coro_rpc_server::stop()

include/ylt/easylog/appender.hpp, include/ylt/standalone/cinatra/time_util.hpp, include/ylt/util/time_util.h, src/coro_http/tests/test_cinatra_websocket.cpp
gmtime, localtime function is not thread safe, should use safe version.
=> [time][fix]call safe time function

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, include/ylt/standalone/cinatra/session_manager.hpp, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_cinatra_websocket.cpp
fix some data race for coro_http.
=> [coro_http]fix data race

.github/workflows/ubuntu_clang.yml, .github/workflows/ubuntu_gcc.yml, cmake/develop.cmake, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/easylog.hpp, src/coro_rpc/tests/CMakeLists.txt, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_parallel.cpp
=> [ci][coro_rpc] fix ci, add parallel test for coro_rpc

include/ylt/metric/summary.hpp, include/ylt/metric/summary_impl.hpp, src/metric/tests/test_metric.cpp
=> [metric]fix missed argument

include/ylt/metric/summary.hpp, src/metric/tests/test_metric.cpp
=> [metric]fix to json

include/ylt/reflection/member_count.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_coro_http_server.cpp, src/coro_rpc/tests/test_parallel.cpp
- fix websocket ping
- fix keep alive
- fix default handler
- fix member count
=> [coro_http_server]fix some

BUILD.bazel, include/ylt/coro_io/client_pool.hpp, include/ylt/coro_io/load_balancer.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, src/coro_http/examples/CMakeLists.txt, src/coro_http/examples/example.cpp, src/coro_http/examples/load_balancer.cpp, src/coro_http/tests/test_coro_http_server.cpp, src/coro_io/tests/CMakeLists.txt, src/coro_io/tests/test_cancel.cpp, src/coro_io/tests/test_client_pool.cpp, src/coro_io/tests/test_load_balancer.cpp, src/coro_rpc/examples/base_examples/CMakeLists.txt, src/coro_rpc/examples/base_examples/load_balancer.cpp, website/docs/zh/coro_http/coro_http_introduction.md
=> [NFC] Fix `blance` typos.

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/error.hpp, src/coro_http/tests/test_cinatra.cpp, src/coro_http/tests/test_mixed.cpp, website/docs/zh/coro_http/coro_http_introduction.md
=> [coro_http_client]add error code

include/ylt/coro_io/coro_io.hpp, include/ylt/coro_rpc/impl/coro_connection.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/coro_rpc/impl/protocol/coro_rpc_protocol.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp, src/coro_rpc/examples/base_examples/server.cpp, src/coro_rpc/examples/user_defined_rpc_protocol/rest_rpc/config/rest_rpc_protocol.hpp, src/coro_rpc/tests/test_coro_rpc_server.cpp
=> add support for http server in rpc port

include/ylt/standalone/cinatra/coro_http_client.hpp, include/ylt/standalone/cinatra/coro_http_connection.hpp, include/ylt/standalone/cinatra/coro_http_server.hpp
- clear head buf when protocol error happend.
- fix start connection, avoid connection lifestyle problem.
=> [coro_http][fix]clear head buf

include/ylt/standalone/cinatra/coro_http_server.hpp
=> [coro_http] fix life-time of transfer_connection

include/ylt/easylog/appender.hpp, include/ylt/util/time_util.h, src/easylog/tests/test_easylog.cpp
replace log timestamp with us.
=> [easylog][feat]log timestamp use us

.github/workflows/ubuntu_clang.yml, .github/workflows/ubuntu_gcc.yml, include/ylt/coro_io/io_context_pool.hpp
=> Fix thread affinity handling on Android platform

include/ylt/standalone/iguana/detail/itoa.hpp
=> [iguana compile]fix compile for mac

README.md, src/coro_http/examples/CMakeLists.txt, src/coro_http/examples/py_example/py_example.cpp, src/coro_http/examples/py_example/test.py, src/coro_rpc/examples/base_examples/CMakeLists.txt, src/coro_rpc/examples/base_examples/coro_rpc_lib/coro_rpc.cpp, src/coro_rpc/examples/base_examples/coro_rpc_lib/coro_rpc.h, src/coro_rpc/examples/base_examples/go_example/test_rpc.go, website/docs/zh/guide/what_is_yalantinglibs.md
Add some examples to show how to use coro_http and coro_rpc with python and golang.
```python
import asyncio
import py_example
async def async_get(url):
loop = asyncio.get_running_loop()
future = loop.create_future()    
def cpp_callback(message):
def set_result():
future.set_result(message)
loop.call_soon_threadsafe(set_result)
caller = py_example.caller(cpp_callback)
caller.async_get(url)
result = await future
print(result)
async def main():
await async_get("http://taobao.com")
if __name__ == "__main__":
asyncio.run(main())
```
```golang
func test_client(host string, len int) {
peer := C.CString(host)
pool := C.create_client_pool(peer, C.int(30))
outbuf := make([]byte, len)
for i := 0; i < 3; i++ {
req_id := uint64(i)
result := C.load(pool, C.uint64_t(req_id), …
```
=> [cross language]Add py and go example for http and rpc

include/ylt/coro_io/socket_wrapper.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp
=> [coro_rpc] Fix reset

include/ylt/coro_io/ibverbs/ib_device.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, src/coro_io/tests/ibverbs/test_device.cpp
=> [rdma]fix mtu

include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_io.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, src/coro_io/tests/ibverbs/test_io.cpp, src/coro_io/tests/ibverbs/test_io2.cpp
=> fix rdma buffer pool

src/coro_rpc/benchmark/bench.cpp
=> [rdma]improve statistic

src/coro_rpc/examples/base_examples/coro_rpc_lib/coro_rpc.cpp, src/coro_rpc/examples/base_examples/coro_rpc_lib/coro_rpc.h, src/coro_rpc/examples/base_examples/go_example/test_rpc.go
update coro_rpc go example for rdma.
=> [coro_rpc][go example]go example enable rdma

include/ylt/coro_io/coro_io.hpp, include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_device.hpp, include/ylt/coro_io/ibverbs/ib_io.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_io/socket_wrapper.hpp, src/coro_rpc/tests/rpc_api.cpp
=> [coro_io] fix ib_socket log & ib_buffer_pool

include/ylt/coro_io/ibverbs/ib_socket.hpp, src/coro_io/tests/ibverbs/test_io.cpp
=> [coro_io][ibverbs] save memory usage

include/ylt/coro_rpc/impl/coro_rpc_client.hpp, src/coro_rpc/tests/test_coro_rpc_client.cpp
Reverts alibaba/yalantinglibs#963
=> Revert "[coro_rpc][feat]rpc client support local ip"

website/docs/zh/metric/metric_introduction.md, website/docs/zh/reflection/reflection_introduction.md
Close #969 
fix and update doc.
=> [no ci]fix and update

.clang-format, cmake/develop.cmake, include/ylt/coro_io/client_pool.hpp, include/ylt/coro_io/coro_io.hpp, include/ylt/coro_io/detail/client_queue.hpp, include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_device.hpp, include/ylt/coro_io/ibverbs/ib_io.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_rpc/impl/coro_connection.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/easylog.hpp, include/ylt/metric/metric.hpp, include/ylt/thirdparty/async_simple/coro/FutureAwaiter.h, src/coro_io/tests/ibverbs/ib_socket_pressure_test.cpp, src/coro_rpc/benchmark/bench.cpp, src/coro_rpc/examples/base_examples/concurrent_clients.cpp, src/coro_rpc/examples/rdma_example/CMakeLists.txt, src/coro_rpc/tests/ServerTester.hpp, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_coro_rpc_server.cpp, src/coro_rpc/tests/test_variadic.cpp
=> [rdma]Fix some rdma bugs

include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp
fix:
- ibverbs resource free order;
- avoid double free fd;
=> [coro_rpc][rdma]fix for free ibverbs resource 

include/ylt/coro_io/ibverbs/ib_device.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/metric/metric.hpp, include/ylt/metric/metric_manager.hpp, src/coro_rpc/benchmark/bench.cpp
- check if enable ibverbs;
- remove some deps
- improve a log;
=> [rdma]fix and update

include/ylt/metric/dynamic_metric.hpp, include/ylt/metric/metric_manager.hpp
=> [metric][fix]add missed header

include/ylt/coro_io/ibverbs/ib_io.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, src/coro_rpc/benchmark/bench.cpp
=> [coro_rpc][rdma]fix buf size

include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_io.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, src/coro_rpc/benchmark/bench.cpp
1. fix a stat bug for ib_buffer_pool
2. fix data race of async_read in ib_socket
3. async_read & async_write of ib_socket now dont need dispatch to io thread, which reduce the latency.
4. fix send failed when got a ib_buffer_t which L_key=0
5. fix post recv buffer queue calculate error size in some case.
=> [coro_io] enhance rdma

include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_device.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_io/socket_wrapper.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/coro_rpc/impl/default_config/coro_rpc_config.hpp, src/coro_io/tests/ibverbs/ib_socket_pressure_test.cpp, src/coro_io/tests/ibverbs/main.cpp, src/coro_io/tests/ibverbs/test_device.cpp, src/coro_io/tests/ibverbs/test_ib_socket.cpp, src/coro_rpc/benchmark/bench.cpp, src/coro_rpc/examples/base_examples/coro_rpc_lib/coro_rpc.cpp, src/coro_rpc/examples/rdma_example/rdma_example.cpp, website/docs/en/coro_rpc/coro_rpc_client.md, website/docs/en/coro_rpc/coro_rpc_server.md, website/docs/zh/coro_rpc/coro_rpc_client.md, website/docs/zh/coro_rpc/coro_rpc_server.md
move ib_buffer_pool_t as a inner member of ib_device_t.
=> move ib_buffer_pool_t as a member of ib_device_t

.github/workflows/s390x.yml, README.md, cmake/build.cmake, cmake/config.cmake, include/ylt/easylog.hpp, include/ylt/util/b_stacktrace.h, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/zh/guide/what_is_yalantinglibs.md
Now ELOG_CRITICAL will output stacktrace to stderr
=> [easylog] support stacktrace

README.md, website/docs/en/guide/what_is_yalantinglibs.md, website/docs/zh/guide/what_is_yalantinglibs.md
=> [no ci][doc] fix document

include/ylt/coro_io/socket_wrapper.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/coro_rpc/impl/coro_rpc_server.hpp, include/ylt/easylog/record.hpp, include/ylt/util/b_stacktrace.h, src/coro_rpc/tests/test_coro_rpc_client.cpp, src/coro_rpc/tests/test_parallel.cpp, website/docs/zh/coro_rpc/coro_rpc_client.md
=> [coro_rpc] fix client reconnect to another address

include/ylt/coro_io/client_pool.hpp, include/ylt/util/ff_ptr.hpp, src/util/tests/CMakeLists.txt, src/util/tests/main.cpp, src/util/tests/test_ff_ptr.cpp
add ff_ptr, which is a util for run-time pointer check
=> [util] add ff_ptr

include/ylt/coro_io/ibverbs/ib_socket.hpp
We should add buffer immediately to avoid rnr error.
=> [coro_io][ibverbs] fix buffer limit

include/ylt/standalone/iguana/json_writer.hpp, include/ylt/standalone/iguana/xml_writer.hpp, include/ylt/standalone/iguana/yaml_writer.hpp
=> [struct_json]check raw pointer

include/ylt/coro_io/client_pool.hpp, include/ylt/coro_io/ibverbs/ib_buffer.hpp, include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/standalone/cinatra/coro_http_client.hpp, src/coro_io/tests/test_client_pool.cpp
=> [coro_io] client pool support limit max live time of client

include/ylt/easylog.hpp
=> [easylog] fix sample log

include/ylt/coro_io/ibverbs/ib_buffer.hpp, src/coro_rpc/benchmark/bench.cpp
=> [ibverbs] add max_recorded_memory_usage()

include/ylt/coro_io/ibverbs/ib_socket.hpp, include/ylt/coro_rpc/impl/coro_rpc_client.hpp, include/ylt/version.hpp, src/coro_rpc/benchmark/bench.cpp
=> [coro_io][ibverbs] fix error handle of fd falsely wake up 

include/ylt/struct_pack/alignment.hpp, include/ylt/struct_pack/reflection.hpp, include/ylt/struct_pack/unpacker.hpp, src/struct_pack/tests/test_compatible.cpp
=> [struct_pack] fix compatible in unordered_map

include/ylt/easylog.hpp
=> feat: make appenders useful
